"""Rectangular QSVT convention helpers for dense validation paths.

The repository's production dense rectangular path uses a PCPhase sequence

    P(phi0), U, P(phi1), U^dagger, P(phi2), ...

on a Julia block encoding.  The high-degree useful-overlap phases generated by
``pyqsp`` symmetric QSP use a different scalar convention.  For odd-degree
``pyqsp`` symmetric phases calibrated with the plus-i scalar signal, the dense
Julia/PCPhase production convention is recovered by shifting every phase by
``pi/2`` and extracting the signed imaginary top-left block.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

PYQSP_TO_PCPHASE_OFFSET = math.pi / 2.0
PYQSP_TO_PCPHASE_RULE = "global_plus_pi_over_2_signed_imag_top_left"
PYQSP_SYM_QSP_PLUS_I = "pyqsp_sym_qsp_plus_i"
DENSE_JULIA_PCPHASE = "dense_julia_pcphase"


@dataclass(frozen=True)
class PCPhaseConversion:
    """Converted production phases plus the required real-valued extraction."""

    phases: np.ndarray
    degree: int
    source_convention: str
    target_convention: str
    phase_mapping: str
    extraction_component: str
    offset: float

    def phase_checksum(self) -> str:
        """Return a stable checksum for the converted phase array."""

        import hashlib

        values = np.ascontiguousarray(self.phases, dtype=np.float64)
        return hashlib.sha256(values.tobytes()).hexdigest()


def pcphase_matrix(
    phase: float,
    *,
    encoded_dimension: int,
    total_dimension: int,
) -> np.ndarray:
    """Return the projector-controlled phase used by the production path."""

    k = int(encoded_dimension)
    dim = int(total_dimension)
    if k <= 0 or k > dim:
        raise ValueError("encoded_dimension must be in (0, total_dimension]")
    diagonal = np.empty(dim, dtype=np.complex128)
    diagonal[:k] = np.exp(1j * float(phase))
    diagonal[k:] = np.exp(-1j * float(phase))
    return np.diag(diagonal)


def pcphase_qsvt_operator(
    block_unitary: np.ndarray,
    phases: np.ndarray,
    *,
    encoded_dimension: int,
) -> np.ndarray:
    """Materialize the production PCPhase/U/Udag QSVT operator."""

    unitary = np.asarray(block_unitary, dtype=np.complex128)
    if unitary.ndim != 2 or unitary.shape[0] != unitary.shape[1]:
        raise ValueError("block_unitary must be square")
    dim = int(unitary.shape[0])
    phase_values = np.asarray(phases, dtype=np.float64)
    if phase_values.ndim != 1 or phase_values.size == 0:
        raise ValueError("phases must be a nonempty one-dimensional array")
    if not np.all(np.isfinite(phase_values)):
        raise ValueError("phases contain non-finite entries")

    operator = pcphase_matrix(
        float(phase_values[0]), encoded_dimension=encoded_dimension, total_dimension=dim
    )
    unitary_dagger = unitary.conj().T
    for index in range(1, phase_values.size - 1, 2):
        operator = unitary @ operator
        operator = (
            pcphase_matrix(
                float(phase_values[index]),
                encoded_dimension=encoded_dimension,
                total_dimension=dim,
            )
            @ operator
        )
        operator = unitary_dagger @ operator
        operator = (
            pcphase_matrix(
                float(phase_values[index + 1]),
                encoded_dimension=encoded_dimension,
                total_dimension=dim,
            )
            @ operator
        )
    if phase_values.size % 2 == 0:
        operator = unitary @ operator
        operator = (
            pcphase_matrix(
                float(phase_values[-1]),
                encoded_dimension=encoded_dimension,
                total_dimension=dim,
            )
            @ operator
        )
    return operator


def pcphase_qsvt_top_block(
    block_unitary: np.ndarray,
    phases: np.ndarray,
    *,
    encoded_dimension: int,
) -> np.ndarray:
    """Return the encoded top-left production QSVT block."""

    operator = pcphase_qsvt_operator(
        block_unitary, phases, encoded_dimension=int(encoded_dimension)
    )
    k = int(encoded_dimension)
    return operator[:k, :k]


def apply_pcphase_qsvt_sequence(
    block_unitary: np.ndarray,
    phases: np.ndarray,
    *,
    encoded_dimension: int,
    vector: np.ndarray,
) -> np.ndarray:
    """Apply the production sequence to a statevector without forming columns."""

    unitary = np.asarray(block_unitary, dtype=np.complex128)
    phase_values = np.asarray(phases, dtype=np.float64)
    if phase_values.ndim != 1 or phase_values.size == 0:
        raise ValueError("phases must be a nonempty one-dimensional array")
    if not np.all(np.isfinite(phase_values)):
        raise ValueError("phases contain non-finite entries")
    state = np.asarray(vector, dtype=np.complex128).copy()
    if state.shape != (unitary.shape[0],):
        raise ValueError("vector dimension must match block_unitary")
    k = int(encoded_dimension)

    def apply_phase(phi: float, values: np.ndarray) -> np.ndarray:
        out = values.copy()
        out[:k] *= np.exp(1j * float(phi))
        out[k:] *= np.exp(-1j * float(phi))
        return out

    state = apply_phase(float(phase_values[0]), state)
    unitary_dagger = unitary.conj().T
    for index in range(1, phase_values.size - 1, 2):
        state = unitary @ state
        state = apply_phase(float(phase_values[index]), state)
        state = unitary_dagger @ state
        state = apply_phase(float(phase_values[index + 1]), state)
    if phase_values.size % 2 == 0:
        state = unitary @ state
        state = apply_phase(float(phase_values[-1]), state)
    return state


def scalar_julia_signal(x: float) -> np.ndarray:
    """Return the scalar Julia block encoding used by the production path."""

    value = float(x)
    if not -1.0 <= value <= 1.0:
        raise ValueError("x must lie in [-1, 1]")
    off = math.sqrt(max(0.0, 1.0 - value * value))
    return np.array([[value, off], [off, -value]], dtype=np.complex128)


def validate_real_rectangular_matrix(matrix: np.ndarray) -> np.ndarray:
    """Validate the matrix scope of the signed-imaginary extraction rule.

    The low-level Julia/PCPhase primitives accept complex unitaries because they
    are useful diagnostic building blocks.  The PyQSP-to-PCPhase convention
    claim in this module is narrower: elementwise imaginary-part extraction
    commutes with the left/right singular-vector factors only for real
    matrices.  Callers entering that claimed path must use this guard.
    """

    values = np.asarray(matrix)
    if values.ndim != 2 or 0 in values.shape:
        raise ValueError("matrix must be a nonempty two-dimensional array")
    if np.iscomplexobj(values):
        raise ValueError(
            "complex matrices are unsupported by the signed-imaginary "
            "rectangular extraction rule"
        )
    real = np.asarray(values, dtype=np.float64)
    if not np.all(np.isfinite(real)):
        raise ValueError("matrix contains non-finite entries")
    return real


def production_scalar_emulator_unitary(x: float, phases: np.ndarray) -> np.ndarray:
    """Evaluate the scalar production PCPhase sequence independently of PyQSP."""

    return pcphase_qsvt_operator(
        scalar_julia_signal(float(x)),
        np.asarray(phases, dtype=np.float64),
        encoded_dimension=1,
    )


def production_scalar_response(
    x: float,
    phases: np.ndarray,
    *,
    component: str = "real",
) -> float:
    """Return a scalar top-left response component from the production emulator."""

    value = production_scalar_emulator_unitary(float(x), phases)[0, 0]
    return float(extract_component(np.array([[value]], dtype=np.complex128), component)[0, 0])


def pyqsp_sym_qsp_to_pcphase_phases(phases: np.ndarray) -> np.ndarray:
    """Map calibrated ``pyqsp`` symmetric-QSP phases into production PCPhase phases."""

    return convert_pyqsp_sym_qsp_to_pcphase(phases, degree=len(phases) - 1).phases


def convert_pyqsp_sym_qsp_to_pcphase(
    phases: np.ndarray,
    *,
    degree: int,
    source_convention: str = PYQSP_SYM_QSP_PLUS_I,
    target_convention: str = DENSE_JULIA_PCPHASE,
    already_converted: bool = False,
) -> PCPhaseConversion:
    """Convert calibrated odd-degree PyQSP phases to production PCPhase phases.

    The conversion is intentionally explicit because raw PyQSP symmetric-QSP
    phases and dense-Julia PCPhase phases are numerically plausible arrays with
    incompatible meaning.  Callers must provide the target odd degree, which is
    used both to validate the phase count and to select the signed imaginary
    extraction component.
    """

    phase_values = np.asarray(phases, dtype=np.float64)
    d = int(degree)
    if already_converted:
        raise ValueError("phases are already marked as dense-Julia PCPhase phases")
    if source_convention != PYQSP_SYM_QSP_PLUS_I:
        raise ValueError(f"unsupported source convention: {source_convention}")
    if target_convention != DENSE_JULIA_PCPHASE:
        raise ValueError(f"unsupported target convention: {target_convention}")
    if d <= 0 or d % 2 == 0:
        raise ValueError("degree must be positive and odd")
    if phase_values.ndim != 1:
        raise ValueError("phases must be one-dimensional")
    if phase_values.size != d + 1:
        raise ValueError("phase count must equal degree + 1")
    if not np.all(np.isfinite(phase_values)):
        raise ValueError("phases contain non-finite entries")
    return PCPhaseConversion(
        phases=phase_values + PYQSP_TO_PCPHASE_OFFSET,
        degree=d,
        source_convention=source_convention,
        target_convention=target_convention,
        phase_mapping=PYQSP_TO_PCPHASE_RULE,
        extraction_component=pyqsp_pcphase_component(d),
        offset=PYQSP_TO_PCPHASE_OFFSET,
    )


def pyqsp_pcphase_imag_sign(degree: int) -> int:
    """Return the sign of the imaginary top-left block for an odd-degree target."""

    d = int(degree)
    if d <= 0 or d % 2 == 0:
        raise ValueError("degree must be positive and odd")
    return -1 if ((d + 1) // 2) % 2 else 1


def pyqsp_pcphase_component(degree: int) -> str:
    """Return the explicit extraction component for mapped pyqsp phases."""

    return "imag" if pyqsp_pcphase_imag_sign(int(degree)) > 0 else "neg_imag"


def extract_component(block: np.ndarray, component: str) -> np.ndarray:
    """Extract a real-valued block component by documented convention name."""

    values = np.asarray(block, dtype=np.complex128)
    if component == "real":
        return np.real(values)
    if component == "imag":
        return np.imag(values)
    if component == "neg_real":
        return -np.real(values)
    if component == "neg_imag":
        return -np.imag(values)
    raise ValueError(f"unknown component: {component}")
