#!/usr/bin/env python3
"""Build the modeled fault-tolerant logical resource estimate table (W2a, must-fix #3).

Rebuilds the four frozen generic sparse-QSVT workloads in memory, verifies each against its
frozen ledger registration (workload digest, matrix hash, final-circuit hash where recorded),
reduces the final measured circuits to an explicit Clifford+T+Rz basis, and applies the
declared Toffoli and Ross--Selinger rotation-synthesis conventions.

Outputs: outputs/ft_logical_resource_estimate/ (rows CSV with per-workload checkpointing,
provenance, manifest, checksums) and manuscript/tables/ft_logical_resource_estimate.tex.
Everything is MODELED-tier: no error-correction, surface-code, or factory model.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
import time
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from robust_qsvt_se.qsvt.ft_resource_estimate import (  # noqa: E402
    CLIFFORD_T_BASIS,
    EPS_ROTATION,
    T_PER_TOFFOLI_EXACT,
    T_PER_TOFFOLI_JONES,
    clifford_t_inventory,
    ft_estimate_record,
    reduce_to_clifford_t,
    ross_selinger_t_count,
)
from robust_qsvt_se.qsvt.ft_workload_rebuild import (  # noqa: E402
    ANCHOR_4X4_ID,
    CANONICAL_ID,
    SCALING_16X16_ID,
    SECOND_ID,
    frozen_ledger_row,
    rebuild_canonical,
    rebuild_dimension_16x16,
    rebuild_dimension_anchor_4x4,
    rebuild_second,
)

OUTPUT_DIR = ROOT / "outputs" / "ft_logical_resource_estimate"
ROWS_PATH = OUTPUT_DIR / "ft_logical_resource_rows.csv"
TABLE_PATH = ROOT / "manuscript" / "tables" / "ft_logical_resource_estimate.tex"
GENERATED_HEADER = "% GENERATED by scripts/build_ft_resource_estimate.py"

WORKLOAD_LABELS = {
    ANCHOR_4X4_ID: r"IEEE-14 $4\times4$, $d=31$ (SV)",
    CANONICAL_ID: r"IEEE-14 $8\times8$, $d=31$ (SV+FS)",
    SECOND_ID: r"IEEE-30 $8\times8$, $d=31$ (SV+FS)",
    SCALING_16X16_ID: r"IEEE-14 $16\times16$, $d=31$ (TO)",
}
WORKLOAD_ORDER = [ANCHOR_4X4_ID, CANONICAL_ID, SECOND_ID, SCALING_16X16_ID]


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _git_commit() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return "unavailable"


def _write_manifest(directory: Path) -> None:
    artifacts = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file() or path.name in {"manifest.json", "checksums.sha256"}:
            continue
        artifacts.append(
            {
                "path": str(path.relative_to(directory)),
                "sha256": _sha256(path),
                "size_bytes": path.stat().st_size,
            }
        )
    (directory / "manifest.json").write_text(
        json.dumps({"artifact_count": len(artifacts), "artifacts": artifacts}, indent=2) + "\n",
        encoding="utf-8",
    )
    (directory / "checksums.sha256").write_text(
        "".join(f"{item['sha256']}  {item['path']}\n" for item in artifacts),
        encoding="utf-8",
    )


def _existing_rows() -> pd.DataFrame:
    if ROWS_PATH.is_file():
        return pd.read_csv(ROWS_PATH)
    return pd.DataFrame()


def _compute_row(workload_id: str, canonical_cache: dict) -> dict:
    started = time.perf_counter()
    if workload_id == CANONICAL_ID:
        compiled = canonical_cache.setdefault("canonical", rebuild_canonical())
    elif workload_id == SECOND_ID:
        compiled = rebuild_second()
    elif workload_id == ANCHOR_4X4_ID:
        canonical = canonical_cache.setdefault("canonical", rebuild_canonical())
        compiled = rebuild_dimension_anchor_4x4(canonical)
    elif workload_id == SCALING_16X16_ID:
        canonical = canonical_cache.setdefault("canonical", rebuild_canonical())
        compiled = rebuild_dimension_16x16(canonical)
    else:
        raise ValueError(f"unknown workload {workload_id}")
    primary = compiled.functional_spec.primary_functional_id
    circuit = compiled.functional_circuits[primary].circuit
    print(f"[ft] {workload_id}: rebuilt+verified in {time.perf_counter() - started:.1f}s",
          flush=True)
    reduce_started = time.perf_counter()
    reduced = reduce_to_clifford_t(circuit)
    inventory = clifford_t_inventory(reduced)
    print(
        f"[ft] {workload_id}: reduced to {inventory['reduced_gate_count']} Clifford+T+Rz "
        f"gates in {time.perf_counter() - reduce_started:.1f}s",
        flush=True,
    )
    record = ft_estimate_record(workload_id, frozen_ledger_row(workload_id), inventory)
    record["primary_functional_id"] = primary
    record["workload_digest"] = compiled.workload_digest
    return record


def _fmt_int(value) -> str:
    return f"{int(value):,}"


def _fmt_sci(value: float, digits: int = 2) -> str:
    value = float(value)
    exponent = int(np.floor(np.log10(abs(value))))
    return rf"${value / 10**exponent:.{digits}f}\times10^{{{exponent}}}$"


def build_table(rows: pd.DataFrame) -> str:
    rows = rows.set_index("workload_id").loc[[w for w in WORKLOAD_ORDER
                                              if w in set(rows["workload_id"])]]
    t_rot = ross_selinger_t_count(EPS_ROTATION)
    max_bound = float(rows["total_synthesis_error_bound"].max())
    bound_exp = int(np.ceil(np.log10(max_bound)))
    min_serial_pct = int(np.floor(100.0 * float(rows["frozen_seriality_fraction"].min())))
    body = []
    for workload_id, row in rows.iterrows():
        body.append(
            " & ".join(
                [
                    WORKLOAD_LABELS[workload_id],
                    _fmt_int(row["qubits"]),
                    _fmt_int(row["frozen_toffoli_count"]),
                    _fmt_int(row["direct_t_count"]),
                    _fmt_int(row["arbitrary_rotation_count"]),
                    _fmt_sci(row["rotation_synthesis_t_count"]),
                    _fmt_sci(row["total_logical_t_count_7t_toffoli"]),
                    _fmt_sci(row["total_logical_t_count_4t_toffoli_jones"]),
                    _fmt_sci(row["serial_clifford_t_depth_estimate"]),
                ]
            )
            + r" \\"
        )
    caption = (
        "Modeled fault-tolerant logical resource estimate for the compiled workloads "
        "(evidence tier: modeled; no error-correction, surface-code, or magic-state factory "
        "model, and no hardware assumptions). Each identity-verified final measured circuit is "
        "reduced to the explicit Clifford$+T$$+R_z$ basis; direct $T$ counts the resulting "
        "$T/T^\\dagger$ gates (Toffolis enter through their exact ancilla-free 7$T$ "
        "decomposition~\\cite{Amy2013}) plus $R_z$ gates at odd multiples of $\\pi/4$. Each of "
        "the $N_{\\rm rot}$ remaining arbitrary rotations is synthesized by the ancilla-free "
        "Ross--Selinger construction~\\cite{RossSelinger2016} at per-rotation accuracy "
        f"$\\epsilon_{{\\rm rot}}=10^{{-10}}$ with leading-order cost $\\lceil 3\\log_2(1/"
        f"\\epsilon_{{\\rm rot}})\\rceil={t_rot}$ $T$/rotation (total synthesis error bound "
        f"$N_{{\\rm rot}}\\epsilon_{{\\rm rot}}\\le 10^{{{bound_exp}}}$ per workload, below "
        "the executed workloads' dominant error terms). The 4$T$ column replaces each ledger "
        "Toffoli's 7$T$ by the measurement-assisted 4$T$ construction~\\cite{Jones2013}. The "
        "depth estimate is the reduced-basis depth with each synthesized rotation expanded "
        f"serially ($2\\times{t_rot}+1$ gates), justified by the measured $\\ge "
        f"{min_serial_pct}\\%$ serial depth of the frozen circuits. SV/FS/TO = statevector / "
        "finite-shot / transpilation-only evidence for the underlying circuit."
    )
    lines = [
        GENERATED_HEADER,
        "% Source: outputs/ft_logical_resource_estimate/ft_logical_resource_rows.csv",
        "% Frozen ledger inputs: outputs/generic_sparse_qsvt_compiler/ (read-only)",
        r"\begin{table*}[t]",
        rf"\caption{{{caption}}}",
        r"\label{tab:ft_logical_resource_estimate}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{@{}lrrrrrrrr@{}}",
        r"\toprule",
        r"Workload & Qubits & Toffolis & Direct $T$ & $N_{\rm rot}$ & Synth.\ $T$ & "
        r"Total $T$ (7$T$) & Total $T$ (4$T$) & Depth est. \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workloads",
        nargs="*",
        default=WORKLOAD_ORDER,
        choices=WORKLOAD_ORDER,
        help="subset to (re)compute; existing rows for other workloads are kept",
    )
    args = parser.parse_args()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    rows = _existing_rows()
    canonical_cache: dict = {}
    for workload_id in args.workloads:
        if len(rows) and workload_id in set(rows.get("workload_id", [])):
            print(f"[ft] {workload_id}: checkpoint present, skipping", flush=True)
            continue
        record = _compute_row(workload_id, canonical_cache)
        rows = pd.concat([rows, pd.DataFrame([record])], ignore_index=True)
        rows.to_csv(ROWS_PATH, index=False)  # durable checkpoint per workload
        print(f"[ft] {workload_id}: checkpointed", flush=True)

    TABLE_PATH.write_text(build_table(rows), encoding="utf-8")

    provenance = {
        "study_id": "ft_logical_resource_estimate_v1",
        "generated_utc": datetime.now(UTC).isoformat(),
        "generator": "scripts/build_ft_resource_estimate.py",
        "git_commit": _git_commit(),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "evidence_tier": "modeled_logical_resource_estimate",
        "clifford_t_basis": list(CLIFFORD_T_BASIS),
        "eps_per_rotation": EPS_ROTATION,
        "t_per_rotation": ross_selinger_t_count(EPS_ROTATION),
        "toffoli_conventions": {
            "primary_exact_7t": T_PER_TOFFOLI_EXACT,
            "alternative_jones_4t": T_PER_TOFFOLI_JONES,
        },
        "citation_keys_required": ["RossSelinger2016", "Jones2013", "Amy2013"],
        "frozen_inputs_read_only": [
            "outputs/generic_sparse_qsvt_compiler/canonical_resource_ledger_generic.csv",
            "outputs/generic_sparse_qsvt_compiler/second_workload_resource_ledger.csv",
            "outputs/generic_sparse_qsvt_compiler/dimension_scaling.csv",
        ],
        "claim_boundary": (
            "Logical Clifford+T accounting only; no surface-code distance, factory, or "
            "physical-qubit claim is made or implied."
        ),
        "manuscript_assets": [str(TABLE_PATH.relative_to(ROOT))],
    }
    (OUTPUT_DIR / "provenance.json").write_text(
        json.dumps(provenance, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _write_manifest(OUTPUT_DIR)
    display = rows[
        [
            "workload_id",
            "frozen_toffoli_count",
            "direct_t_count",
            "arbitrary_rotation_count",
            "total_logical_t_count_7t_toffoli",
            "serial_clifford_t_depth_estimate",
        ]
    ]
    print(display.to_string(index=False))


if __name__ == "__main__":
    main()
