"""Goal C: combined component error-budget table for the selected-output workload.

Reads only values that were actually generated by repository experiments; missing
sources are recorded as ``not available`` with the expected file path. The table
is an accounting boundary, not a closed end-to-end error theorem.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

OUTPUT_DIR = Path("outputs/qsvt_error_budget")

WORKLOAD = Path("outputs/qsvt_selected_workload_extension/selected_workload_results.csv")
BE_REPORT = Path("outputs/ieee_qsvt_pipeline_boundary/block_encoding_report.csv")
STATE_PREP = Path("outputs/ieee_qsvt_pipeline_boundary/state_preparation_report.csv")
LOOKUP = Path(
    "outputs/tqe_revision_experiments/sparse_block_encoding_demo/reconstructed_block_error.csv"
)
QUANT = Path("outputs/sparse_quantization_error_report/quantization_error_report.csv")
WRAPPER = Path("outputs/sparse_block_encoding_wrapper_demo/wrapper_demo_results.csv")
READOUT = Path(
    "outputs/tqe_revision_experiments/readout_statistics/readout_shot_scaling_summary.csv"
)
RESOURCE = Path(
    "outputs/tqe_revision_experiments/end_to_end_resource_case/fixed_case_resource_ledger.csv"
)
NONLINEAR_TABLE = Path("manuscript/tables/nonlinear_convergence_revision.tex")

COLUMNS = [
    "component",
    "symbol",
    "source_table_or_script",
    "scale",
    "measured_modeled_or_excluded",
    "value_or_range",
    "included_in_current_resource_count",
    "limitation",
]


def _read(path: Path) -> pd.DataFrame | None:
    return pd.read_csv(path) if path.is_file() else None


def _fmt(value: float) -> str:
    return f"{value:.3e}"


def build_rows() -> list[dict[str, str]]:
    workload = _read(WORKLOAD)
    be_report = _read(BE_REPORT)
    state_prep = _read(STATE_PREP)
    lookup = _read(LOOKUP)
    quant = _read(QUANT)
    wrapper = _read(WRAPPER)
    readout = _read(READOUT)
    resource = _read(RESOURCE)

    def workload_value(workload_id: str, column: str) -> float | None:
        if workload is None:
            return None
        rows = workload[workload["workload_id"] == workload_id]
        return float(rows.iloc[0][column]) if len(rows) else None

    anchor_fit = workload_value("anchor_4x4_benchmark_alpha_d31", "target_fit_error")
    secondary_fit = workload_value("8x8_codesigned_lambda_matched_d31", "target_fit_error")
    anchor_svt = workload_value("anchor_4x4_benchmark_alpha_d31", "circuit_vs_exact_svt_error")
    anchor_unitarity = workload_value(
        "anchor_4x4_benchmark_alpha_d31", "dense_block_encoding_unitarity_error"
    )

    def resource_value(field: str) -> str | None:
        if resource is None:
            return None
        rows = resource[resource["field"] == field]
        return str(rows.iloc[0]["value"]) if len(rows) else None

    rows: list[dict[str, str]] = []

    rows.append(
        {
            "component": "polynomial approximation error",
            "symbol": r"$\epsilon_{\mathrm{poly}}$",
            "source_table_or_script": "scripts/run_selected_workload_extension.py",
            "scale": "4x4 anchor / 8x8 secondary anchor (degree 31)",
            "measured_modeled_or_excluded": "measured",
            "value_or_range": (
                f"{_fmt(anchor_fit)} (4x4); {_fmt(secondary_fit)} (8x8)"
                if anchor_fit is not None and secondary_fit is not None
                else "not available (missing outputs/qsvt_selected_workload_extension)"
            ),
            "included_in_current_resource_count": "yes (sets feasible degree)",
            "limitation": "max error of the bounded odd fit on the synthesis domain",
        }
    )
    rows.append(
        {
            "component": "phase-synthesis / circuit SVT error",
            "symbol": r"$\epsilon_{\mathrm{SVT}}$",
            "source_table_or_script": "scripts/run_selected_workload_extension.py",
            "scale": "4x4 anchor circuit",
            "measured_modeled_or_excluded": "measured (statevector)",
            "value_or_range": (_fmt(anchor_svt) if anchor_svt is not None else "not available"),
            "included_in_current_resource_count": "no (subdominant to shot noise)",
            "limitation": "gate-level QSVT operator vs exact polynomial SVT",
        }
    )
    rows.append(
        {
            "component": "dense block-encoding unitarity error",
            "symbol": r"$\epsilon_{U}$",
            "source_table_or_script": (
                "outputs/ieee_qsvt_pipeline_boundary/block_encoding_report.csv"
            ),
            "scale": "selected 4x4--16x16 blocks",
            "measured_modeled_or_excluded": "measured (statevector)",
            "value_or_range": (
                f"{_fmt(anchor_unitarity)} (anchor); worst "
                f"{_fmt(float(be_report['unitarity_error'].max()))} across selected blocks"
                if be_report is not None and anchor_unitarity is not None
                else "not available"
            ),
            "included_in_current_resource_count": "no (negligible at this scale)",
            "limitation": "dense dilation only; not a scalable encoding",
        }
    )
    rows.append(
        {
            "component": "dense block reconstruction error",
            "symbol": r"$\epsilon_{\mathrm{TL}}$",
            "source_table_or_script": (
                "outputs/ieee_qsvt_pipeline_boundary/block_encoding_report.csv"
            ),
            "scale": "selected 4x4--16x16 blocks",
            "measured_modeled_or_excluded": "measured (statevector)",
            "value_or_range": (
                f"{_fmt(float(be_report['top_left_block_error'].max()))} (max)"
                if be_report is not None
                else "not available"
            ),
            "included_in_current_resource_count": "no",
            "limitation": "top-left block vs normalized target matrix",
        }
    )
    rows.append(
        {
            "component": "sparse lookup logical reconstruction error",
            "symbol": r"$\epsilon_{\mathrm{lookup}}$",
            "source_table_or_script": (
                "outputs/tqe_revision_experiments/sparse_block_encoding_demo/"
                "reconstructed_block_error.csv"
            ),
            "scale": "compiled 4x4 and 8x8 lookup circuits",
            "measured_modeled_or_excluded": "measured (statevector)",
            "value_or_range": (
                f"{_fmt(float(lookup['max_abs_error_vs_quantized'].max()))} vs quantized words "
                "(bit-exact)"
                if lookup is not None
                else "not available"
            ),
            "included_in_current_resource_count": "no",
            "limitation": "logical correctness of O_col/O_val only; not a block encoding",
        }
    )
    rows.append(
        {
            "component": "sparse lookup quantization error",
            "symbol": r"$\epsilon_{\mathrm{quant}}$",
            "source_table_or_script": (
                "outputs/sparse_quantization_error_report/quantization_error_report.csv"
            ),
            "scale": "six-bit words, 4x4 and 8x8 blocks",
            "measured_modeled_or_excluded": "measured",
            "value_or_range": (
                "relative Frobenius "
                + "; ".join(
                    f"{row.relative_frobenius_error:.2%} ({row.matrix_shape})"
                    for row in quant.itertuples()
                )
                if quant is not None
                else "not available"
            ),
            "included_in_current_resource_count": "no (representation choice)",
            "limitation": "fixed-point step of the compiled value words",
        }
    )
    rows.append(
        {
            "component": "quantized selected-output propagated error",
            "symbol": r"$\Delta y_{\mathrm{quant}}$",
            "source_table_or_script": (
                "outputs/sparse_quantization_error_report/quantization_error_report.csv"
            ),
            "scale": "matched-alpha selected output",
            "measured_modeled_or_excluded": "measured",
            "value_or_range": (
                "; ".join(
                    f"{row.relative_selected_output_error:.2%} ({row.matrix_shape})"
                    for row in quant.itertuples()
                )
                if quant is not None
                else "not available"
            ),
            "included_in_current_resource_count": "no",
            "limitation": "propagation of six-bit words through the matched update",
        }
    )
    rows.append(
        {
            "component": "full sparse block-encoding wrapper error",
            "symbol": r"$\epsilon_{\mathrm{wrap}}$",
            "source_table_or_script": "scripts/run_sparse_block_encoding_wrapper_demo.py",
            "scale": "toy 4x4 sparsified quantized block",
            "measured_modeled_or_excluded": "measured (toy); modeled at scale",
            "value_or_range": (
                f"reconstruction {_fmt(float(wrapper.iloc[0]['top_left_reconstruction_error']))}"
                f"; QSVT-through-wrapper update error "
                f"{_fmt(float(wrapper.iloc[0]['qsvt_integration_update_rel_error']))}"
                if wrapper is not None
                else "not available (wrapper demo not run)"
            ),
            "included_in_current_resource_count": "no",
            "limitation": (
                "exact only for the derived sparsified block; IEEE-scale wrapper not compiled"
            ),
        }
    )
    rows.append(
        {
            "component": "residual-state preparation error",
            "symbol": r"$\epsilon_{\mathrm{prep}}$",
            "source_table_or_script": (
                "outputs/ieee_qsvt_pipeline_boundary/state_preparation_report.csv"
            ),
            "scale": "selected blocks (dense loading) / full matrices (model)",
            "measured_modeled_or_excluded": "measured (blocks); modeled (full scale)",
            "value_or_range": (
                f"L2 error {_fmt(float(state_prep['state_preparation_l2_error'].max()))} (blocks); "
                "full scale: no compiled loader, cost model O(2^{q_r})"
                if state_prep is not None
                else "not available"
            ),
            "included_in_current_resource_count": "yes (T_prep repeats per attempt)",
            "limitation": "no scalable structured residual loader is compiled",
        }
    )
    rows.append(
        {
            "component": "postselection probability uncertainty/source",
            "symbol": r"$p_{\mathrm{succ}}$",
            "source_table_or_script": (
                "outputs/tqe_revision_experiments/end_to_end_resource_case/"
                "fixed_case_resource_ledger.csv"
            ),
            "scale": "4x4 circuit / selected blocks / sweep proxy",
            "measured_modeled_or_excluded": "measured (circuit); modeled (proxy)",
            "value_or_range": (
                f"{resource_value('postselection_probability')} (circuit, prepared residual); "
                "block statevector estimates 4.4e-08--0.66; uniform-input proxy in sweep"
                if resource_value("postselection_probability") is not None
                else "not available"
            ),
            "included_in_current_resource_count": "yes (1/p_succ repeats)",
            "limitation": "three distinct definitions; each table states which one it uses",
        }
    )
    rows.append(
        {
            "component": "isolated signed-overlap shot error",
            "symbol": r"$\epsilon_{\mathrm{shot}}$",
            "source_table_or_script": (
                "outputs/tqe_revision_experiments/readout_statistics/"
                "readout_shot_scaling_summary.csv"
            ),
            "scale": "4x4 isolated overlap circuit, 30 seeds",
            "measured_modeled_or_excluded": "measured under assumed output-state preparation",
            "value_or_range": (
                _pooled_readout_range(readout) if readout is not None else "not available"
            ),
            "included_in_current_resource_count": "modeled composition only",
            "limitation": (
                "direct StatePreparation of computed output; not integrated with loader, "
                "QSVT, or postselection"
            ),
        }
    )
    rows.append(
        {
            "component": "classical adjoint numerical agreement",
            "symbol": r"$|y_{\mathrm{adj}}-y_{\mathrm{ridge}}|$",
            "source_table_or_script": "scripts/run_selected_workload_extension.py",
            "scale": "all feasible workload rows",
            "measured_modeled_or_excluded": "measured",
            "value_or_range": (
                _fmt(
                    float(
                        (workload["classical_adjoint_value"] - workload["ridge_reference_value"])
                        .abs()
                        .max()
                    )
                )
                + " (max abs)"
                if workload is not None
                else "not available"
            ),
            "included_in_current_resource_count": "reference only",
            "limitation": "same functional, same alpha; different cost units than queries",
        }
    )
    rows.append(
        {
            "component": "nonlinear-iteration accumulation error",
            "symbol": r"$\epsilon_{\mathrm{NL}}$",
            "source_table_or_script": "manuscript/tables/nonlinear_convergence_revision.tex",
            "scale": "IEEE 14/30/57 Gauss-Newton loops",
            "measured_modeled_or_excluded": "excluded",
            "value_or_range": (
                "excluded: QSVT is not executed inside the loop; classical pinv and Ridge "
                "trajectories coincide at reported precision"
                if NONLINEAR_TABLE.is_file()
                else "not available"
            ),
            "included_in_current_resource_count": "no",
            "limitation": "interface and consistency check only",
        }
    )
    return rows


def _pooled_readout_range(readout: pd.DataFrame) -> str:
    pooled = readout[readout["observable_label"] == "__all_signed_pooled__"]
    if pooled.empty:
        return "not available"
    low = pooled.loc[pooled["shots"].idxmin()]
    high = pooled.loc[pooled["shots"].idxmax()]
    return (
        f"pooled mean relative {low['mean_relative_error_vs_ridge']:.3e} at "
        f"{int(low['shots'])} shots to {high['mean_relative_error_vs_ridge']:.3e} at "
        f"{int(high['shots'])} shots"
    )


def _tex_escape(text: str) -> str:
    out = text.replace("{", r"\{").replace("}", r"\}")
    for char, repl in [
        ("&", r"\&"),
        ("%", r"\%"),
        ("_", r"\_"),
        ("#", r"\#"),
        ("^", "\\textasciicircum{}"),
        ("~", "\\textasciitilde{}"),
    ]:
        out = out.replace(char, repl)
    return out


def _write_tex(frame: pd.DataFrame, path: Path) -> None:
    lines = [
        r"% Source: outputs/qsvt_error_budget/error_budget.csv",
        r"% Regenerate: .venv/bin/python scripts/build_qsvt_error_budget_table.py",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Combined component error budget for the selected-submatrix QSVT workload. "
        r"Every value is taken from a generated repository artifact; components without a "
        r"compiled realization are labeled modeled or excluded. This table is an accounting "
        r"boundary, not a closed end-to-end error theorem.}",
        r"\label{tab:error_budget}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{p{0.16\textwidth}p{0.05\textwidth}p{0.13\textwidth}p{0.12\textwidth}"
        r"p{0.28\textwidth}p{0.14\textwidth}}",
        r"\hline",
        r"Component & Symbol & Scale & Status & Value or range & Limitation \\",
        r"\hline",
    ]
    for _, row in frame.iterrows():
        cells = [
            _tex_escape(str(row["component"])),
            str(row["symbol"]),
            _tex_escape(str(row["scale"])),
            _tex_escape(str(row["measured_modeled_or_excluded"])),
            _tex_escape(str(row["value_or_range"])),
            _tex_escape(str(row["limitation"])),
        ]
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table*}", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def _to_markdown(frame: pd.DataFrame) -> str:
    headers = [str(c) for c in frame.columns]
    rows = [[str(v) for v in row] for row in frame.itertuples(index=False)]
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(cell.replace("|", "/") for cell in row) + " |" for row in rows]
    return "\n".join(lines)


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    frame = pd.DataFrame(build_rows(), columns=COLUMNS)
    frame.to_csv(OUTPUT_DIR / "error_budget.csv", index=False)
    _write_tex(frame, OUTPUT_DIR / "error_budget.tex")
    md_lines = [
        "# Combined QSVT Selected-Output Error Budget (Goal C)",
        "",
        "Accounting boundary for the component errors of the selected-output workload; "
        "not a closed end-to-end error theorem. Values come only from generated artifacts.",
        "",
        _to_markdown(frame),
        "",
    ]
    (OUTPUT_DIR / "error_budget.md").write_text("\n".join(md_lines), encoding="utf-8")
    manifest = {
        "artifact_name": "qsvt_error_budget",
        "sources": {
            "workload": str(WORKLOAD),
            "block_encoding_report": str(BE_REPORT),
            "state_preparation_report": str(STATE_PREP),
            "lookup_reconstruction": str(LOOKUP),
            "quantization_report": str(QUANT),
            "wrapper_demo": str(WRAPPER),
            "readout_statistics": str(READOUT),
            "fixed_case_resource_ledger": str(RESOURCE),
            "nonlinear_table": str(NONLINEAR_TABLE),
        },
        "regeneration_command": ".venv/bin/python scripts/build_qsvt_error_budget_table.py",
        "note": "accounting boundary, not a closed end-to-end error theorem",
    }
    (OUTPUT_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"Error budget written to {OUTPUT_DIR} ({len(frame)} rows)")


if __name__ == "__main__":
    main()
