#!/usr/bin/env python3
"""Robust companion statistics for the four pre-declared primary contrasts (W6, rec #8).

Additive extension of the frozen structure-level statistics: reads the frozen
``structure_level_summary.csv`` (never rewriting any frozen artifact), forms the identical
12 paired structure effects per contrast with the frozen ``_paired_values`` helper, and adds
an exact sign test and a Wilcoxon signed-rank test with Holm adjustment over the pre-declared
family of four contrasts.  Consistency with the frozen bootstrap summaries is asserted, not
assumed.

Outputs: outputs/robust_companion_statistics/ (CSV, provenance, manifest, checksums) and
manuscript/tables/robust_companion_statistics.tex.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import binomtest, wilcoxon

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from robust_qsvt_se.physical_alignment.statistics import _paired_values  # noqa: E402

AUDIT_DIR = ROOT / "outputs" / "tqe_physical_alignment_and_generalization" / "physical_audit"
OUTPUT_DIR = ROOT / "outputs" / "robust_companion_statistics"
TABLE_PATH = ROOT / "manuscript" / "tables" / "robust_companion_statistics.tex"
GENERATED_HEADER = "% GENERATED by scripts/build_robust_companion_statistics.py"

# The pre-declared primary family (identical to whole_project_primary_effects.tex).
PRIMARY_CONTRASTS = (
    ("sensitivity_refined_mean", "global_magnitude", "E_support",
     "Sensitivity vs. magnitude", r"$E_{\rm support}$"),
    ("sensitivity_refined_mean", "global_magnitude", "E_physical",
     "Sensitivity vs. magnitude", r"$E_{\rm physical}$"),
    ("noise_propagation_risk_mean_refined", "global_magnitude", "E_physical",
     "Noise-risk vs. magnitude", r"$E_{\rm physical}$"),
    ("posterior_variance_reference_mean_refined", "global_magnitude", "E_physical",
     "Posterior-var. vs. magnitude", r"$E_{\rm physical}$"),
)
CONTRAST_COUNT = len(PRIMARY_CONTRASTS)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _assert_legacy_csv_matches_frozen(csv_path: Path, checksums_path: Path) -> None:
    # The legacy evidence CSV is a frozen artifact; manuscript-only regeneration
    # must never silently consume a byte-modified copy. Fail fast on hash drift
    # so an altered historical record cannot reach a publication-facing table.
    if not checksums_path.is_file() or not csv_path.is_file():
        return
    expected = None
    for line in checksums_path.read_text(encoding="utf-8").splitlines():
        parts = line.split(None, 1)
        if len(parts) == 2 and parts[1].strip() == csv_path.name:
            expected = parts[0].lower()
            break
    if expected is None:
        return
    actual = _sha256(csv_path)
    if actual != expected:
        raise SystemExit(
            f"frozen evidence hash mismatch for {csv_path.name}: expected {expected}, "
            f"got {actual}; refusing to rebuild the publication-facing table from "
            f"altered historical evidence."
        )


def _git_commit() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return "unavailable"


def _write_manifest(directory: Path) -> None:
    artifacts = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file() or path.name in {"manifest.json", "checksums.sha256"}:
            continue
        artifacts.append(
            {
                "path": str(path.relative_to(directory)),
                "sha256": _sha256(path),
                "size_bytes": path.stat().st_size,
            }
        )
    (directory / "manifest.json").write_text(
        json.dumps({"artifact_count": len(artifacts), "artifacts": artifacts}, indent=2) + "\n",
        encoding="utf-8",
    )
    (directory / "checksums.sha256").write_text(
        "".join(f"{item['sha256']}  {item['path']}\n" for item in artifacts),
        encoding="utf-8",
    )


def _frozen_mean_effect(candidate: str, baseline: str, metric: str) -> tuple[float, float, float]:
    """Frozen observed mean effect and case-stratified CI for the consistency assertion."""

    if metric == "E_support":
        frame = pd.read_csv(AUDIT_DIR / "support_fidelity_pairwise_summary.csv")
        row = frame.loc[
            (frame["candidate_selector"] == candidate)
            & (frame["baseline_selector"] == baseline)
        ].iloc[0]
    else:
        frame = pd.read_csv(AUDIT_DIR / "selector_pairwise_summary.csv")
        row = frame.loc[
            (frame["candidate_selector"] == candidate)
            & (frame["baseline_selector"] == baseline)
        ].iloc[0]
    return (
        float(row["observed_mean_effect"]),
        float(row["case_stratified_ci_low"]),
        float(row["case_stratified_ci_high"]),
    )


def holm_adjust(p_values: list[float]) -> list[float]:
    """Holm step-down adjustment over the pre-declared contrast family."""

    order = np.argsort(p_values)
    m = len(p_values)
    adjusted = [0.0] * m
    running = 0.0
    for rank, index in enumerate(order):
        value = min(1.0, (m - rank) * p_values[index])
        running = max(running, value)
        adjusted[index] = running
    return adjusted


def compute_rows() -> pd.DataFrame:
    structure = pd.read_csv(AUDIT_DIR / "structure_level_summary.csv")
    records: list[dict] = []
    for candidate, baseline, metric, label, metric_label in PRIMARY_CONTRASTS:
        paired = _paired_values(structure, candidate, baseline, metric=metric)
        effects = paired["effect"].to_numpy(dtype=np.float64)
        if len(effects) != 12:
            raise RuntimeError(
                f"{candidate} vs {baseline} [{metric}]: expected 12 paired structures, "
                f"found {len(effects)}"
            )
        frozen_mean, ci_low, ci_high = _frozen_mean_effect(candidate, baseline, metric)
        if not np.isclose(effects.mean(), frozen_mean, rtol=0, atol=1.0e-12):
            raise RuntimeError(
                f"{candidate} vs {baseline} [{metric}]: paired mean {effects.mean()} "
                f"disagrees with frozen observed_mean_effect {frozen_mean}"
            )
        positive = int(np.sum(effects > 0.0))
        negative = int(np.sum(effects < 0.0))
        ties = int(np.sum(effects == 0.0))
        sign = binomtest(positive, positive + negative, p=0.5, alternative="two-sided")
        wil = wilcoxon(effects, alternative="two-sided", method="exact")
        records.append(
            {
                "candidate_selector": candidate,
                "baseline_selector": baseline,
                "metric": metric,
                "contrast_label": label,
                "metric_label": metric_label,
                "paired_structure_count": len(effects),
                "effect_definition": "baseline error minus candidate error (>0 favors candidate)",
                "n_positive": positive,
                "n_negative": negative,
                "n_ties": ties,
                "mean_effect": float(effects.mean()),
                "median_effect": float(np.median(effects)),
                "frozen_observed_mean_effect": frozen_mean,
                "frozen_case_stratified_ci_low": ci_low,
                "frozen_case_stratified_ci_high": ci_high,
                "frozen_ci_excludes_zero": bool(ci_low > 0.0 or ci_high < 0.0),
                "sign_test_p_exact": float(sign.pvalue),
                "wilcoxon_statistic": float(wil.statistic),
                "wilcoxon_p_exact": float(wil.pvalue),
                "consistent_with_frozen_mean": True,
            }
        )
    frame = pd.DataFrame(records)
    frame["sign_test_p_holm"] = holm_adjust(list(frame["sign_test_p_exact"]))
    frame["wilcoxon_p_holm"] = holm_adjust(list(frame["wilcoxon_p_exact"]))
    frame["pre_declared_contrast_count"] = CONTRAST_COUNT

    def verdict(row: pd.Series) -> str:
        wilcoxon_significant = row["wilcoxon_p_holm"] < 0.05
        same_direction = np.sign(row["mean_effect"]) == np.sign(
            row["frozen_observed_mean_effect"]
        )
        if wilcoxon_significant and row["frozen_ci_excludes_zero"] and same_direction:
            return "significant_same_direction_as_bootstrap"
        if (not wilcoxon_significant) and (not row["frozen_ci_excludes_zero"]):
            return "inconclusive_consistent_with_bootstrap"
        return "partially_consistent_see_columns"

    frame["agreement_with_bootstrap"] = frame.apply(verdict, axis=1)
    frame["sign_test_holm_significant"] = frame["sign_test_p_holm"] < 0.05
    frame["wilcoxon_holm_significant"] = frame["wilcoxon_p_holm"] < 0.05
    return frame


def _outcome_sentence(rows: pd.DataFrame) -> str:
    """Caption summary computed from the results, never asserted in advance."""

    parts: list[str] = []
    for row in rows.itertuples():
        direction = "favoring the candidate" if row.mean_effect > 0 else "favoring the baseline"
        if row.agreement_with_bootstrap == "significant_same_direction_as_bootstrap":
            state = (
                f"Wilcoxon-significant after Holm ({_fmt_p(row.wilcoxon_p_holm)}), "
                f"{direction}, matching the bootstrap interval"
            )
            if not row.sign_test_holm_significant:
                state += (
                    "; the lower-powered exact sign test does not reach Holm-adjusted "
                    f"significance ({_fmt_p(row.sign_test_p_holm)})"
                )
        elif row.agreement_with_bootstrap == "inconclusive_consistent_with_bootstrap":
            state = (
                f"inconclusive under both robust tests ({_fmt_p(row.wilcoxon_p_holm)}), "
                "matching the zero-covering bootstrap interval"
            )
        else:
            state = (
                f"partially consistent (Wilcoxon Holm {_fmt_p(row.wilcoxon_p_holm)}, sign "
                f"Holm {_fmt_p(row.sign_test_p_holm)}, bootstrap excludes zero: "
                f"{row.frozen_ci_excludes_zero})"
            )
        parts.append(
            f"{row.contrast_label} on {_publication_metric_label(row.metric_label)} is {state}"
        )
    return "; ".join(parts) + "."


def _fmt_p(value: float) -> str:
    value = float(value)
    if value >= 0.001:
        return f"{value:.3f}"
    exponent = int(np.floor(np.log10(value)))
    return rf"${value / 10**exponent:.1f}\times10^{{{exponent}}}$"


def _publication_metric_label(label: str) -> str:
    """Map the legacy evidence label without rewriting the historical CSV."""

    return str(label).replace(r"E_{\rm physical}", r"E_{\rm benchmark}")


def build_table(rows: pd.DataFrame) -> str:
    body = []
    for row in rows.itertuples():
        body.append(
            " & ".join(
                [
                    row.contrast_label,
                    _publication_metric_label(row.metric_label),
                    f"{row.n_positive}/{row.n_positive + row.n_negative}",
                    _fmt_p(row.sign_test_p_exact),
                    _fmt_p(row.wilcoxon_p_exact),
                    _fmt_p(row.sign_test_p_holm),
                    _fmt_p(row.wilcoxon_p_holm),
                ]
            )
            + r" \\"
        )
    caption = (
        "Robust companion statistics for the four pre-declared primary contrasts "
        "(distribution-free complements to the case-stratified bootstrap intervals of the "
        "primary-effects table; the raw rows and bootstrap summaries are unchanged). Each "
        "test uses the identical 12 paired structure effects (baseline error minus candidate "
        "error, positive favors the candidate; zero effects are dropped by both tests, so "
        "``Favor'' reports wins over informative pairs). The sign test is the exact binomial "
        "test on effect signs; the Wilcoxon signed-rank test uses the exact null "
        "distribution; Holm columns adjust each test over the pre-declared family of four "
        "contrasts. " + _outcome_sentence(rows)
    )
    lines = [
        GENERATED_HEADER,
        "% Source: outputs/robust_companion_statistics/robust_companion_statistics.csv",
        "% Frozen inputs (read-only): outputs/tqe_physical_alignment_and_generalization/"
        "physical_audit/",
        r"\begin{table*}[t]",
        rf"\caption{{{caption}}}",
        r"\label{tab:robust_companion_statistics}",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.8pt}",
        r"\begin{tabular}{@{}llrrrrr@{}}",
        r"\toprule",
        r"Contrast & Metric & Favor & Sign $p$ & Wilcoxon $p$ & Sign $p$ (Holm) & "
        r"Wilcoxon $p$ (Holm) \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manuscript-only",
        action="store_true",
        help="regenerate only the publication-facing table from the legacy evidence CSV",
    )
    args = parser.parse_args()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if args.manuscript_only:
        legacy_csv = OUTPUT_DIR / "robust_companion_statistics.csv"
        _assert_legacy_csv_matches_frozen(legacy_csv, OUTPUT_DIR / "checksums.sha256")
        rows = pd.read_csv(legacy_csv)
        TABLE_PATH.write_text(build_table(rows), encoding="utf-8")
        print(TABLE_PATH)
        return

    rows = compute_rows()
    rows.to_csv(OUTPUT_DIR / "robust_companion_statistics.csv", index=False)

    caption_guard = rows["agreement_with_bootstrap"].tolist()
    TABLE_PATH.write_text(build_table(rows), encoding="utf-8")

    provenance = {
        "study_id": "robust_companion_statistics_v1",
        "generated_utc": datetime.now(UTC).isoformat(),
        "generator": "scripts/build_robust_companion_statistics.py",
        "git_commit": _git_commit(),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "pre_declared_contrast_count": CONTRAST_COUNT,
        "statistical_unit": "structural_group_id (12 paired structures; 3 IEEE cases)",
        "tests": ["exact_sign_test_binomial", "wilcoxon_signed_rank_exact",
                  "holm_step_down_family_of_4"],
        "frozen_inputs_read_only": [
            "outputs/tqe_physical_alignment_and_generalization/physical_audit/"
            "structure_level_summary.csv",
            "outputs/tqe_physical_alignment_and_generalization/physical_audit/"
            "selector_pairwise_summary.csv",
            "outputs/tqe_physical_alignment_and_generalization/physical_audit/"
            "support_fidelity_pairwise_summary.csv",
        ],
        "consistency_assertion": (
            "paired means asserted equal to frozen observed_mean_effect at atol 1e-12"
        ),
        "agreement_with_bootstrap": caption_guard,
        "manuscript_assets": [str(TABLE_PATH.relative_to(ROOT))],
    }
    (OUTPUT_DIR / "provenance.json").write_text(
        json.dumps(provenance, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _write_manifest(OUTPUT_DIR)
    print(
        rows[
            [
                "contrast_label",
                "metric",
                "n_positive",
                "n_negative",
                "sign_test_p_exact",
                "wilcoxon_p_exact",
                "sign_test_p_holm",
                "wilcoxon_p_holm",
                "frozen_ci_excludes_zero",
                "agreement_with_bootstrap",
            ]
        ].to_string(index=False)
    )


if __name__ == "__main__":
    main()
