#!/usr/bin/env python3
"""Generate the final Figure-1 Ridge/Tikhonov spectral-filter panel.

Every plotted sample is evaluated directly from

    f_alpha(sigma) = sigma / (sigma**2 + alpha)   and   f_pinv(sigma) = 1 / sigma.

The preferred variant uses the *repository* regularization of the canonical
IEEE-14 sparse 8x8 d=31 workload, read from the frozen candidate freeze and
re-derived from the quantized block as alpha = 4 * sigma_min_positive(H_q)**2.
A clearly separated illustrative variant at alpha = 1e-2 is also emitted so the
conceptual reading remains available; it is never presented as experimental data.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
from pathlib import Path
import tempfile

_CACHE_ROOT = Path(tempfile.gettempdir()) / "qsvt_figure1_plot_cache"
_CACHE_ROOT.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(_CACHE_ROOT / "matplotlib"))
os.environ.setdefault("XDG_CACHE_HOME", str(_CACHE_ROOT / "xdg"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import FixedLocator, NullLocator
import numpy as np
from PIL import Image

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CANDIDATE_FREEZE = REPOSITORY_ROOT / "outputs" / "joint_four_condition" / "candidate_freeze.json"
CHAIN_METADATA = (
    REPOSITORY_ROOT / "outputs" / "sparse_chain_reconciliation" / "end_to_end_run" / "matrix_metadata.json"
)
QUANTIZED_BLOCK = (
    REPOSITORY_ROOT / "outputs" / "sparse_chain_reconciliation" / "end_to_end_run" / "matrix_quantized.npy"
)

ILLUSTRATIVE_ALPHA = 1.0e-2
N_SAMPLES = 6001
PORTRAIT_FIGSIZE_IN = (2.40, 3.80)
PORTRAIT_DPI = 600
PREVIEW_WIDTH_IN = 1.80
PREVIEW_DPI = 300
RIDGE_COLOR = "#2F6F9F"
REFERENCE_COLOR = "#3F3F3F"
ANNOTATION_COLOR = "#6A6A6A"

# Positive-singular-value cut used by the canonical chain (phase10 module, line 337).
SIGMA_POSITIVE_TOLERANCE = 1.0e-10


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPOSITORY_ROOT))
    except ValueError:
        return str(path)


def ridge_filter(sigma: np.ndarray | float, alpha: float) -> np.ndarray:
    """Exact Ridge/Tikhonov spectral response."""

    values = np.asarray(sigma, dtype=float)
    return values / (values**2 + alpha)


def pseudoinverse_filter(sigma: np.ndarray | float) -> np.ndarray:
    """Exact positive-singular-value pseudoinverse response."""

    return 1.0 / np.asarray(sigma, dtype=float)


def _array_sha256(values: np.ndarray) -> str:
    payload = np.ascontiguousarray(np.asarray(values, dtype=np.float64)).tobytes()
    return hashlib.sha256(payload).hexdigest()


def resolve_repository_alpha() -> dict[str, object]:
    """Read the canonical alpha and independently re-derive it from H_q."""

    freeze = json.loads(CANDIDATE_FREEZE.read_text(encoding="utf-8"))
    chain = json.loads(CHAIN_METADATA.read_text(encoding="utf-8"))
    frozen_alpha = float(freeze["alpha"])
    if float(chain["alpha"]) != frozen_alpha:
        raise RuntimeError("candidate freeze and chain metadata disagree on alpha")

    quantized = np.load(QUANTIZED_BLOCK, allow_pickle=False)
    if _array_sha256(quantized) != str(freeze["component_hashes"]["matrix_quantized"]):
        raise RuntimeError("quantized block artifact does not match the frozen hash")

    singular_values = np.linalg.svd(quantized, compute_uv=False)
    positive = singular_values[singular_values > SIGMA_POSITIVE_TOLERANCE]
    derived_alpha = 4.0 * float(positive.min()) ** 2
    if derived_alpha != frozen_alpha:
        raise RuntimeError(
            f"alpha re-derivation mismatch: frozen {frozen_alpha!r}, derived {derived_alpha!r}"
        )

    beta = float(freeze["beta"])
    normalized_lambda = float(freeze["normalized_lambda"])
    if abs(frozen_alpha - normalized_lambda * beta * beta) != 0.0:
        raise RuntimeError("alpha does not satisfy alpha = lambda * beta**2 exactly")

    return {
        "alpha": frozen_alpha,
        "alpha_role": "repository-derived canonical workload regularization",
        "alpha_provenance": (
            "outputs/joint_four_condition/candidate_freeze.json:alpha; identical in "
            "outputs/sparse_chain_reconciliation/end_to_end_run/matrix_metadata.json:alpha; "
            "generated by src/robust_qsvt_se/paper/phase10_sparse_wrapper_8x8_complete.py:338 "
            "as alpha = 4 * sigma_min_positive(H_q)**2"
        ),
        "workload_id": str(freeze["workload_id"]),
        "sigma_min_positive_quantized": float(positive.min()),
        "sigma_max_quantized": float(singular_values.max()),
        "quantized_rank_positive": int(positive.size),
        "quantized_singular_values": [float(v) for v in singular_values],
        "beta": beta,
        "normalized_lambda": normalized_lambda,
        "alpha_equals_lambda_beta_squared": True,
        "alpha_equals_four_sigma_min_squared": True,
        "sigma_axis_scale_source": "singular values of the canonical quantized block H_q",
    }


def _configure_style() -> None:
    plt.rcParams.update(
        {
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
            "font.family": "serif",
            "font.serif": ["STIXGeneral", "Times New Roman", "Times", "DejaVu Serif"],
            "mathtext.fontset": "stix",
            "font.size": 9.0,
            "axes.labelsize": 10.5,
            "xtick.labelsize": 7.4,
            "ytick.labelsize": 8.6,
            "axes.linewidth": 0.65,
            "xtick.major.width": 0.60,
            "ytick.major.width": 0.60,
            "xtick.major.size": 3.0,
            "ytick.major.size": 3.0,
            "xtick.direction": "out",
            "ytick.direction": "out",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
            "svg.hashsalt": "figure1-ridge-final",
            "path.simplify": False,
        }
    )


def _build_portrait_figure(
    *,
    alpha: float,
    decade_exponents: tuple[int, ...],
    y_limit: float,
    y_ticks: tuple[float, ...],
    y_scale_exponent: int | None,
    label_positions: dict[str, tuple[float, float]],
) -> tuple[plt.Figure, dict[str, object]]:
    if not math.isfinite(alpha) or alpha <= 0.0:
        raise ValueError("alpha must be finite and strictly positive")

    sigma_min = 10.0 ** decade_exponents[0]
    sigma_max = 10.0 ** decade_exponents[-1]
    sigma = np.logspace(math.log10(sigma_min), math.log10(sigma_max), N_SAMPLES, dtype=float)
    ridge = ridge_filter(sigma, alpha)
    pinv = pseudoinverse_filter(sigma)

    sigma_star = math.sqrt(alpha)
    analytic_maximum = 1.0 / (2.0 * sigma_star)
    sampled_index = int(np.argmax(ridge))
    sampled_sigma_maximum = float(sigma[sampled_index])
    sampled_filter_maximum = float(ridge[sampled_index])

    # The verified quantities are the exact arrays handed to Matplotlib below.
    assert float(ridge_filter(0.0, alpha)) == 0.0
    assert math.isclose(sampled_sigma_maximum, sigma_star, rel_tol=2.0e-4, abs_tol=0.0)
    assert math.isclose(sampled_filter_maximum, analytic_maximum, rel_tol=2.0e-8, abs_tol=0.0)
    assert np.all(np.diff(ridge[: sampled_index + 1]) > 0.0)
    assert np.all(np.diff(ridge[sampled_index:]) < 0.0)
    assert np.all(np.diff(pinv) < 0.0)
    assert sigma_min < sigma_star < sigma_max

    _configure_style()
    fig, ax = plt.subplots(figsize=PORTRAIT_FIGSIZE_IN)
    fig.subplots_adjust(left=0.268, right=0.940, bottom=0.150, top=0.945)

    ax.axvline(
        sigma_star,
        color=ANNOTATION_COLOR,
        linewidth=0.75,
        linestyle=(0, (2.2, 2.2)),
        alpha=0.72,
        zorder=1,
    )
    (pinv_line,) = ax.plot(
        sigma,
        pinv,
        color=REFERENCE_COLOR,
        linewidth=1.00,
        linestyle=(0, (4.2, 2.7)),
        dash_capstyle="butt",
        zorder=2,
    )
    (ridge_line,) = ax.plot(
        sigma,
        ridge,
        color=RIDGE_COLOR,
        linewidth=1.70,
        solid_capstyle="round",
        zorder=3,
    )

    ax.set_xscale("log")
    ax.set_yscale("linear")
    ax.set_xlim(sigma_min, sigma_max)
    ax.set_ylim(0.0, y_limit)
    ax.set_xlabel(r"Singular value $\sigma$", labelpad=4.0)
    ax.set_ylabel("Filter value", labelpad=4.0)

    decade_ticks = np.power(10.0, np.asarray(decade_exponents, dtype=float))
    decade_labels = [rf"$10^{{{exponent}}}$" for exponent in decade_exponents]
    ax.xaxis.set_major_locator(FixedLocator(decade_ticks))
    ax.set_xticklabels(decade_labels)
    ax.xaxis.set_minor_locator(NullLocator())

    ax.set_yticks(list(y_ticks))
    if y_scale_exponent is None:
        y_tick_labels = [f"{value:g}" for value in y_ticks]
    else:
        factor = 10.0**y_scale_exponent
        y_tick_labels = [f"{value / factor:g}" for value in y_ticks]
    ax.set_yticklabels(y_tick_labels)
    if y_scale_exponent is not None:
        ax.text(
            0.0,
            1.012,
            rf"$\times 10^{{{y_scale_exponent}}}$",
            transform=ax.transAxes,
            fontsize=7.4,
            color="#303030",
            ha="left",
            va="bottom",
        )
    ax.tick_params(axis="x", which="major", pad=2.0)
    ax.tick_params(axis="y", which="major", pad=2.2)

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color("#303030")
    ax.spines["bottom"].set_color("#303030")
    ax.grid(False)

    ax.text(
        *label_positions["ridge"],
        r"$f_\alpha(\sigma)$",
        color=RIDGE_COLOR,
        fontsize=9.6,
        ha="left",
        va="bottom",
        zorder=4,
    )
    ax.text(
        *label_positions["pinv"],
        r"$1/\sigma$",
        color=REFERENCE_COLOR,
        fontsize=9.3,
        ha="left",
        va="bottom",
        zorder=4,
    )
    ax.annotate(
        r"$\sqrt{\alpha}$",
        xy=(sigma_star, 0.0),
        xytext=(5.0, 8.0),
        textcoords="offset points",
        color=ANNOTATION_COLOR,
        fontsize=8.8,
        ha="left",
        va="bottom",
        annotation_clip=False,
        zorder=4,
    )

    assert np.array_equal(np.asarray(ridge_line.get_xdata()), sigma)
    assert np.array_equal(np.asarray(ridge_line.get_ydata()), ridge)
    assert np.array_equal(np.asarray(pinv_line.get_xdata()), sigma)
    assert np.array_equal(np.asarray(pinv_line.get_ydata()), pinv)
    assert ax.get_xscale() == "log"
    assert ax.get_yscale() == "linear"
    assert np.array_equal(ax.get_xticks(), decade_ticks)
    assert [tick.get_text() for tick in ax.get_xticklabels()] == decade_labels
    assert ax.get_title() == ""
    assert ax.get_legend() is None
    assert not any(line.get_visible() for line in ax.get_xgridlines() + ax.get_ygridlines())

    verification: dict[str, object] = {
        "filter_formula": "f_alpha(sigma) = sigma / (sigma**2 + alpha)",
        "reference_formula": "f_pinv(sigma) = 1 / sigma",
        "alpha": alpha,
        "sigma_min_plotted": sigma_min,
        "sigma_max_plotted": sigma_max,
        "n_samples": N_SAMPLES,
        "sqrt_alpha_analytic": sigma_star,
        "sqrt_alpha_sampled": sampled_sigma_maximum,
        "sqrt_alpha_sampled_relative_error": abs(sampled_sigma_maximum - sigma_star) / sigma_star,
        "ridge_maximum_analytic": analytic_maximum,
        "ridge_maximum_sampled": sampled_filter_maximum,
        "peak_location_equals_sqrt_alpha": True,
        "ridge_at_zero": 0.0,
        "ridge_increases_through_sqrt_alpha": True,
        "ridge_decreases_after_sqrt_alpha": True,
        "pseudoinverse_strictly_decreasing": True,
        "all_curve_samples_formula_evaluated": True,
        "x_axis_logarithmic": True,
        "y_axis_linear": True,
        "x_tick_exponents": list(decade_exponents),
        "y_ticks": list(y_ticks),
        "y_scale_exponent": y_scale_exponent,
        "grid_enabled": False,
        "embedded_title_caption_or_legend": False,
        "direct_labels": ["f_alpha(sigma)", "1/sigma", "sqrt(alpha)"],
        "figure_width_in": PORTRAIT_FIGSIZE_IN[0],
        "figure_height_in": PORTRAIT_FIGSIZE_IN[1],
        "width_to_height_ratio": PORTRAIT_FIGSIZE_IN[0] / PORTRAIT_FIGSIZE_IN[1],
        "portrait_layout": PORTRAIT_FIGSIZE_IN[1] > PORTRAIT_FIGSIZE_IN[0],
    }
    return fig, verification


def _write_preview(source_png: Path, preview_png: Path) -> tuple[int, int]:
    width_px = round(PREVIEW_WIDTH_IN * PREVIEW_DPI)
    height_px = round(width_px * PORTRAIT_FIGSIZE_IN[1] / PORTRAIT_FIGSIZE_IN[0])
    with Image.open(source_png) as image:
        image.convert("RGB").resize((width_px, height_px), Image.Resampling.LANCZOS).save(
            preview_png, format="PNG", dpi=(PREVIEW_DPI, PREVIEW_DPI), optimize=True
        )
    return width_px, height_px


def _emit(
    fig: plt.Figure,
    verification: dict[str, object],
    *,
    pdf_dir: Path,
    svg_dir: Path,
    png_dir: Path,
    stem: str,
) -> dict[str, object]:
    pdf_path = pdf_dir / f"{stem}.pdf"
    svg_path = svg_dir / f"{stem}.svg"
    png_path = png_dir / f"{stem}.png"
    preview_path = png_dir / f"{stem}_preview.png"

    fig.savefig(pdf_path, format="pdf", transparent=False)
    fig.savefig(svg_path, format="svg", transparent=False)
    fig.savefig(png_path, format="png", dpi=PORTRAIT_DPI, transparent=False)
    plt.close(fig)

    width_px, height_px = _write_preview(png_path, preview_path)
    verification.update(
        {
            "main_png_dpi": PORTRAIT_DPI,
            "manuscript_size_preview_dpi": PREVIEW_DPI,
            "manuscript_size_preview_width_in": PREVIEW_WIDTH_IN,
            "manuscript_size_preview_px": [width_px, height_px],
        }
    )
    return {
        "pdf": _display_path(pdf_path),
        "svg": _display_path(svg_path),
        "png": _display_path(png_path),
        "manuscript_size_preview": _display_path(preview_path),
    }


def generate(output_root: Path) -> dict[str, object]:
    pdf_dir = output_root / "pdf"
    svg_dir = output_root / "svg"
    png_dir = output_root / "png"
    for directory in (pdf_dir, svg_dir, png_dir):
        directory.mkdir(parents=True, exist_ok=True)

    repository_alpha = resolve_repository_alpha()
    alpha = float(repository_alpha["alpha"])

    canonical_fig, canonical_check = _build_portrait_figure(
        alpha=alpha,
        decade_exponents=(1, 2, 3, 4, 5),
        y_limit=6.0e-4,
        y_ticks=(0.0, 2.0e-4, 4.0e-4, 6.0e-4),
        y_scale_exponent=-4,
        label_positions={"ridge": (1.15e1, 1.32e-4), "pinv": (7.6e3, 1.98e-4)},
    )
    canonical_check.update(repository_alpha)
    canonical_check["alpha_classification"] = "repository-derived canonical workload value"
    canonical_outputs = _emit(
        canonical_fig,
        canonical_check,
        pdf_dir=pdf_dir,
        svg_dir=svg_dir,
        png_dir=png_dir,
        stem="figure1_ridge_spectral_filter_final",
    )

    illustrative_fig, illustrative_check = _build_portrait_figure(
        alpha=ILLUSTRATIVE_ALPHA,
        decade_exponents=(-3, -2, -1, 0, 1, 2, 3),
        y_limit=6.2,
        y_ticks=(0.0, 2.0, 4.0, 6.0),
        y_scale_exponent=None,
        label_positions={"ridge": (1.15e-3, 1.38), "pinv": (2.8e-1, 4.22)},
    )
    illustrative_check["alpha_classification"] = "conceptual illustrative value, not experimental data"
    illustrative_check["alpha_provenance"] = "figure-only illustrative choice; absent from manuscript and repository configuration"
    illustrative_outputs = _emit(
        illustrative_fig,
        illustrative_check,
        pdf_dir=pdf_dir,
        svg_dir=svg_dir,
        png_dir=png_dir,
        stem="figure1_ridge_spectral_filter_final_illustrative",
    )

    payload = {
        "preferred_variant": "repository_derived_canonical_alpha",
        "canonical": {"outputs": canonical_outputs, "verification": canonical_check},
        "illustrative": {"outputs": illustrative_outputs, "verification": illustrative_check},
    }
    verification_path = pdf_dir / "figure1_ridge_spectral_filter_final_verification.json"
    verification_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    payload["verification_json"] = _display_path(verification_path)
    return payload


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", type=Path, default=REPOSITORY_ROOT / "output")
    args = parser.parse_args()
    print(json.dumps(generate(args.output_root), indent=2))


if __name__ == "__main__":
    main()
