#!/usr/bin/env python3
"""Run the benchmark-reference-validity vs block-size study and emit manuscript assets.

Purely classical full-support study (no circuits, no selector): nested outcome-independent
blocks per IEEE case, generated-benchmark-reference error under two declared alpha policies.

Outputs: outputs/physical_validity_vs_block_size/ (CSVs, provenance, manifest, checksums),
manuscript/tables/physical_validity_vs_block_size.tex,
manuscript/figures/fig_physical_validity_vs_block_size.pdf.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from robust_qsvt_se.cross_case_validation.block_size_validity import (  # noqa: E402
    ALPHA_POLICIES,
    CASES,
    STUDY_ID,
    run_study,
)

OUTPUT_DIR = ROOT / "outputs" / "physical_validity_vs_block_size"
TABLE_PATH = ROOT / "manuscript" / "tables" / "physical_validity_vs_block_size.tex"
FIGURE_PATH = ROOT / "manuscript" / "figures" / "fig_physical_validity_vs_block_size.pdf"
GENERATED_HEADER = "% GENERATED by scripts/run_physical_validity_vs_block_size.py"
CASE_COLORS = {"ieee14": "#0072B2", "ieee30": "#D55E00", "ieee57": "#009E73"}
CASE_LABELS = {"ieee14": "IEEE-14", "ieee30": "IEEE-30", "ieee57": "IEEE-57"}
CASE_STYLES = {
    "ieee14": {"marker": "o", "linestyle": "-"},
    "ieee30": {"marker": "s", "linestyle": (0, (4.0, 1.8))},
    "ieee57": {"marker": "^", "linestyle": "-."},
}
POLICY_LABELS = {
    "matched_frozen_benchmark": r"(a) Workload-matched $\alpha$ policy",
    "design_4sigma_min": r"(b) Uniform $\alpha=4\sigma_{\min}^{2}$ policy",
}


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _git_commit() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except Exception:
        return "unavailable"


def _write_manifest(directory: Path) -> None:
    artifacts = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file() or path.name in {"manifest.json", "checksums.sha256"}:
            continue
        artifacts.append(
            {
                "path": str(path.relative_to(directory)),
                "sha256": _sha256(path),
                "size_bytes": path.stat().st_size,
            }
        )
    (directory / "manifest.json").write_text(
        json.dumps({"artifact_count": len(artifacts), "artifacts": artifacts}, indent=2)
        + "\n",
        encoding="utf-8",
    )
    (directory / "checksums.sha256").write_text(
        "".join(f"{item['sha256']}  {item['path']}\n" for item in artifacts),
        encoding="utf-8",
    )


def _fmt(value: float, digits: int = 3) -> str:
    value = float(value)
    if not np.isfinite(value):
        return "--"
    if value != 0.0 and (abs(value) < 1.0e-3 or abs(value) >= 1.0e3):
        exponent = int(np.floor(np.log10(abs(value))))
        return rf"${value / 10**exponent:.{digits - 1}f}\times10^{{{exponent}}}$"
    return f"{value:.{digits}f}"


def _size_order(label: str) -> int:
    return 10**9 if label == "full" else int(label.split("x")[0])


def build_table(frames: dict[str, pd.DataFrame]) -> str:
    summary = frames["summary"]
    inventory = frames["inventory"].set_index(["case", "size_label"])
    pivot = summary.pivot_table(
        index=["case", "size_label"],
        columns="alpha_policy",
        values="median_E_physical_norm",
        aggfunc="first",
    )
    body: list[str] = []
    for case in CASES:
        labels = sorted(
            {label for (c, label) in pivot.index if c == case}, key=_size_order
        )
        for label in labels:
            inv = inventory.loc[(case, label)]
            matched = float(pivot.loc[(case, label), "matched_frozen_benchmark"])
            design = float(pivot.loc[(case, label), "design_4sigma_min"])
            shape = (
                f"{int(inv['block_rows'])}$\\times${int(inv['block_cols'])}"
                if label == "full"
                else label.replace("x", "$\\times$")
            )
            tag = " (full)" if label == "full" else ""
            body.append(
                f"{CASE_LABELS[case]} & {shape}{tag} & "
                f"{float(inv['state_coverage_fraction']):.2f} & {int(inv['rank'])} & "
                f"{int(inv['n_physical_functionals'])} & "
                f"{_fmt(matched)} & {_fmt(design)} \\\\"
            )
        body.append(r"\addlinespace")
    while body and body[-1] == r"\addlinespace":
        body.pop()
    constants = frames["constants"].iloc[0]
    caption = (
        "Full-support benchmark-reference error versus selected-block size "
        "(classical study; no circuits and no support selector). Blocks are extracted with the "
        "frozen outcome-independent largest-row/column-norm rule; each cell is the median of "
        f"$E_{{\\rm benchmark}}$ over {int(constants['n_held_out_seeds'])} held-out residual "
        "seeds and all representable registered functionals (near-zero references excluded), the "
        "stage-one aggregation of the main benchmark-reference audit with one extractor realization per "
        "size. The matched policy reuses the frozen IEEE-14 $8\\times8$ manuscript "
        "regularization and the $4\\sigma_{\\min}^2$ design rule elsewhere; the uniform policy "
        "applies the design rule at every size. IEEE-14 $32\\times32$ and larger square blocks "
        "exceed the state dimension and are structurally unavailable. Functional counts grow "
        "with block size because more states, branches, and connected areas become "
        "representable."
    )
    lines = [
        GENERATED_HEADER,
        f"% Source: outputs/physical_validity_vs_block_size/ ({STUDY_ID})",
        r"\begin{table*}[t]",
        rf"\caption{{{caption}}}",
        r"\label{tab:physical_validity_vs_block_size}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}llrrrrr@{}}",
        r"\toprule",
        r"Case & Block & State cov. & Rank & Functionals & "
        r"Median $E_{\rm benchmark}$ (matched) & Median $E_{\rm benchmark}$ (design) \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
    ]
    return "\n".join(lines) + "\n"


def build_figure(frames: dict[str, pd.DataFrame]) -> None:
    summary = frames["summary"]
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 8.0,
            "axes.titlesize": 9.2,
            "axes.labelsize": 9.0,
            "legend.fontsize": 8.0,
            "xtick.labelsize": 8.0,
            "ytick.labelsize": 8.0,
            "axes.linewidth": 0.8,
            "lines.linewidth": 1.7,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    fig, axes = plt.subplots(
        1,
        2,
        figsize=(7.16, 3.05),
        constrained_layout=True,
        sharey=True,
    )
    for ax, policy in zip(axes, ALPHA_POLICIES, strict=True):
        subset = summary[summary["alpha_policy"] == policy]
        for case in CASES:
            group = subset[subset["case"] == case].copy()
            group = group.sort_values("size_label", key=lambda s: s.map(_size_order))
            x = group["block_cols"].to_numpy(dtype=np.float64)
            y = group["median_E_physical_norm"].to_numpy(dtype=np.float64)
            square = (group["size_label"] != "full").to_numpy()
            style = CASE_STYLES[case]
            ax.plot(
                x,
                y,
                linewidth=1.75,
                linestyle=style["linestyle"],
                color=CASE_COLORS[case],
                zorder=2,
            )
            ax.scatter(
                x[square],
                y[square],
                s=31,
                marker=style["marker"],
                facecolors=CASE_COLORS[case],
                edgecolors="#303030",
                linewidths=0.35,
                zorder=4,
            )
            ax.scatter(
                x[~square],
                y[~square],
                s=59,
                marker="o",
                facecolors="white",
                edgecolors=CASE_COLORS[case],
                linewidths=1.55,
                zorder=5,
            )
        ax.set_xscale("log", base=2)
        ax.set_yscale("log")
        ax.margins(x=0.10)
        ax.set_title(POLICY_LABELS[policy], pad=7)
        ax.grid(axis="y", which="major", color="#CFCFCF", linewidth=0.55)
        ax.grid(axis="y", which="minor", color="#E5E5E5", linewidth=0.4)
        ax.set_axisbelow(True)
        ax.spines[["top", "right"]].set_visible(False)
    common_ylim = axes[0].get_ylim()
    for ax in axes:
        ax.set_ylim(common_ylim)
    fig.supxlabel(r"Number of selected matrix columns ($\log_2$ scale)")
    axes[0].set_ylabel(r"Median $E_{\mathrm{bench}}$ (log scale)")
    legend_handles = [
        Line2D(
            [],
            [],
            color=CASE_COLORS[case],
            linestyle=CASE_STYLES[case]["linestyle"],
            marker=CASE_STYLES[case]["marker"],
            markerfacecolor=CASE_COLORS[case],
            markeredgecolor="#303030",
            markeredgewidth=0.35,
            markersize=5.2,
            label=CASE_LABELS[case],
        )
        for case in CASES
    ]
    legend_handles.append(
        Line2D(
            [],
            [],
            color="#4D4D4D",
            linestyle="none",
            marker="o",
            markerfacecolor="white",
            markeredgecolor="#4D4D4D",
            markeredgewidth=1.35,
            markersize=6.2,
            label="Complete system",
        )
    )
    axes[0].legend(
        handles=legend_handles,
        frameon=False,
        loc="lower left",
        ncol=2,
        handlelength=2.5,
        columnspacing=1.0,
        handletextpad=0.55,
    )
    FIGURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(
        FIGURE_PATH,
        bbox_inches="tight",
        pad_inches=0.02,
        metadata={"Creator": __file__},
    )
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--assets-only",
        action="store_true",
        help=(
            "Regenerate only the manuscript table and figure from existing canonical CSVs; "
            "do not rerun or rewrite the scientific evidence, provenance, manifest, or checksums."
        ),
    )
    args = parser.parse_args()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    file_names = {
        "raw": "raw_full_support_rows.csv",
        "summary": "block_size_summary.csv",
        "family_summary": "family_summary.csv",
        "trend": "trend_assessment.csv",
        "nestedness": "block_nestedness.csv",
        "inventory": "block_inventory.csv",
        "constants": "protocol_constants.csv",
    }
    if args.assets_only:
        frames = {
            key: pd.read_csv(OUTPUT_DIR / name)
            for key, name in file_names.items()
        }
    else:
        frames = run_study(str(OUTPUT_DIR / "_frozen_cache"))
        for key, name in file_names.items():
            frames[key].to_csv(OUTPUT_DIR / name, index=False)

    TABLE_PATH.write_text(build_table(frames), encoding="utf-8")
    build_figure(frames)

    if args.assets_only:
        print(
            f"[{STUDY_ID}] manuscript assets regenerated from existing canonical CSVs; "
            "scientific evidence and registries unchanged"
        )
        return

    provenance = {
        "study_id": STUDY_ID,
        "generated_utc": datetime.now(UTC).isoformat(),
        "generator": "scripts/run_physical_validity_vs_block_size.py",
        "git_commit": _git_commit(),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "package_versions": {
            "numpy": np.__version__,
            "pandas": pd.__version__,
        },
        "evidence_tier": "classical exact computation (no circuit execution)",
        "claim_boundary": (
            "Full-support generated-benchmark-reference error only; selector behavior, QSVT "
            "feasibility, and circuit resources at larger sizes are out of scope."
        ),
        "manuscript_assets": [
            str(TABLE_PATH.relative_to(ROOT)),
            str(FIGURE_PATH.relative_to(ROOT)),
        ],
    }
    (OUTPUT_DIR / "provenance.json").write_text(
        json.dumps(provenance, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _write_manifest(OUTPUT_DIR)

    trend = frames["trend"]
    print(f"[{STUDY_ID}] raw rows: {len(frames['raw'])}")
    for row in trend.itertuples():
        print(
            f"  {row.case} [{row.alpha_policy}] medians {row.median_sequence} "
            f"monotone_nonincreasing={row.monotonic_nonincreasing} "
            f"full/8x8 ratio={row.ratio_full_to_8x8:.4f}"
        )


if __name__ == "__main__":
    main()
