#!/usr/bin/env python3
"""Run the depolarizing noise-model boundary study (W2b, must-fix #3).

Simulates the identity-verified smallest executed circuit (IEEE-14 4x4, degree-31 anchor;
7 qubits; 60,587 frozen default-target gates) on the Aer density-matrix method under a uniform
depolarizing model (same p on every 1q rz/sx/x and 2q cx basis gate), with exact noisy
readout distributions plus genuine sampled Aer counts at fixed seeds.

Outputs: outputs/noise_model_boundary/ (CSVs, provenance, manifest, checksums),
manuscript/tables/noise_model_boundary.tex,
manuscript/figures/fig_noise_model_boundary.pdf.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from robust_qsvt_se.qsvt.ft_workload_rebuild import (  # noqa: E402
    ANCHOR_4X4_ID,
    rebuild_canonical,
    rebuild_dimension_anchor_4x4,
)
from robust_qsvt_se.qsvt.noise_model_boundary import (  # noqa: E402
    DEPOLARIZING_SWEEP,
    NOISE_BASIS,
    SAMPLING_SEEDS,
    SHOTS_PER_SEED,
    build_depolarizing_model,
    exact_noisy_joint_distribution,
    exact_noisy_marginal_zero,
    noise_basis_gate_counts,
    reduce_to_noise_basis,
    sampled_noisy_counts,
    selected_output_from_distribution,
)

OUTPUT_DIR = ROOT / "outputs" / "noise_model_boundary"
CHECKPOINT_PATH = OUTPUT_DIR / "checkpoints.jsonl"
TABLE_PATH = ROOT / "manuscript" / "tables" / "noise_model_boundary.tex"
FIGURE_PATH = ROOT / "manuscript" / "figures" / "fig_noise_model_boundary.pdf"
GENERATED_HEADER = "% GENERATED by scripts/run_noise_model_boundary.py"


def _load_checkpoints() -> dict[str, dict]:
    if not CHECKPOINT_PATH.is_file():
        return {}
    entries: dict[str, dict] = {}
    for line in CHECKPOINT_PATH.read_text(encoding="utf-8").splitlines():
        if line.strip():
            payload = json.loads(line)
            entries[payload["key"]] = payload["value"]
    return entries


def _checkpoint(key: str, value: dict) -> None:
    with CHECKPOINT_PATH.open("a", encoding="utf-8") as stream:
        stream.write(json.dumps({"key": key, "value": value}, sort_keys=True) + "\n")
        stream.flush()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _git_commit() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return "unavailable"


def _write_manifest(directory: Path) -> None:
    artifacts = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file() or path.name in {"manifest.json", "checksums.sha256"}:
            continue
        artifacts.append(
            {
                "path": str(path.relative_to(directory)),
                "sha256": _sha256(path),
                "size_bytes": path.stat().st_size,
            }
        )
    (directory / "manifest.json").write_text(
        json.dumps({"artifact_count": len(artifacts), "artifacts": artifacts}, indent=2) + "\n",
        encoding="utf-8",
    )
    (directory / "checksums.sha256").write_text(
        "".join(f"{item['sha256']}  {item['path']}\n" for item in artifacts),
        encoding="utf-8",
    )


def _sci(value: float, digits: int = 2) -> str:
    value = float(value)
    if value == 0.0:
        return "0"
    exponent = int(np.floor(np.log10(abs(value))))
    return rf"${value / 10**exponent:.{digits}f}\times10^{{{exponent}}}$"


def _outcome_sentence(exact: pd.DataFrame) -> str:
    """Data-derived caption sentence; written after, never before, the sweep."""

    by_p = exact.set_index("depolarizing_p")
    parts = []
    for p in sorted(p for p in by_p.index if p > 0):
        retention = float(by_p.loc[p, "signal_retention_fraction"])
        parts.append(rf"$p=10^{{{int(np.log10(p))}}}$: {100.0 * retention + 0.0:.1f}\%")
    return "Signal retention is " + "; ".join(parts) + "."


def build_table(
    exact: pd.DataFrame, sampled: pd.DataFrame, gates: dict, reference: dict
) -> str:
    body = []
    for p in sorted(exact["depolarizing_p"].unique()):
        row = exact[exact["depolarizing_p"] == p].iloc[0]
        srows = sampled[sampled["depolarizing_p"] == p]
        p_label = "0 (ideal)" if p == 0.0 else _sci(p, 0)
        body.append(
            " & ".join(
                [
                    p_label,
                    _sci(row["selected_output"], 3),
                    _sci(row["absolute_error_vs_ideal"], 2)
                    if row["absolute_error_vs_ideal"] > 0
                    else "0",
                    f"{float(row['signal_retention_fraction']) + 0.0:.4f}",
                    f"{row['direct_postselection_acceptance']:.4f}",
                    _sci(srows["absolute_error_vs_ideal"].mean(), 2),
                    _sci(srows["selected_output"].std(ddof=1), 2),
                ]
            )
            + r" \\"
        )
    caption = (
        "Depolarizing noise boundary for the smallest executed sparse-QSVT circuit "
        f"(IEEE-14 $4\\times4$, degree-31 anchor; {reference['qubits']} qubits; "
        f"{gates['total_noisy_gates']:,} noisy gates after reduction to the "
        f"{'/'.join(NOISE_BASIS)} basis: {gates['noisy_one_qubit_gates']:,} one-qubit and "
        f"{gates['noisy_two_qubit_gates']:,} two-qubit). A uniform depolarizing channel with "
        "the same parameter $p$ acts after every one- and two-qubit basis gate. Exact columns "
        "come from the noisy density matrix (no shot noise); sampled columns are genuine Aer "
        f"density-matrix counts ({SHOTS_PER_SEED:,} shots $\\times$ {len(SAMPLING_SEEDS)} "
        "fixed seeds; evidence tier: noisy simulator execution). Retention is the noisy "
        "selected output divided by the ideal statevector reference "
        f"({_sci(reference['statevector_selected_output'], 3)}). "
        + _outcome_sentence(exact)
        + " This is an executed quantitative boundary, not a hardware-readiness claim."
    )
    lines = [
        GENERATED_HEADER,
        "% Source: outputs/noise_model_boundary/exact_noise_rows.csv and "
        "sampled_noise_rows.csv",
        r"\begin{table*}[t]",
        rf"\caption{{{caption}}}",
        r"\label{tab:noise_model_boundary}",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.6pt}",
        r"\begin{tabular}{@{}lrrrrrr@{}}",
        r"\toprule",
        r"$p$ & Exact $y$ & Exact err. & Retention & $p_{\rm post}$ & "
        r"Sampled err.\ (mean) & Seed std. \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
    ]
    return "\n".join(lines) + "\n"


def build_figure(exact: pd.DataFrame, sampled: pd.DataFrame, reference: dict) -> None:
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(7.15, 2.9), constrained_layout=True)
    positive = exact[exact["depolarizing_p"] > 0].sort_values("depolarizing_p")
    p_values = positive["depolarizing_p"].to_numpy(dtype=np.float64)

    ax1.plot(
        p_values,
        positive["absolute_error_vs_ideal"],
        marker="o",
        markersize=4.5,
        linewidth=2.0,
        color="#276FBF",
        label="exact noisy error",
    )
    grouped = (
        sampled[sampled["depolarizing_p"] > 0]
        .groupby("depolarizing_p")["absolute_error_vs_ideal"]
        .agg(["mean", "min", "max"])
        .reindex(p_values)
    )
    ax1.scatter(
        p_values,
        grouped["mean"],
        s=26,
        color="#C14953",
        zorder=5,
        label="sampled mean error",
    )
    ax1.vlines(
        p_values, grouped["min"], grouped["max"], color="#C14953", linewidth=1.2, alpha=0.8
    )
    ideal_abs = abs(float(reference["statevector_selected_output"]))
    ax1.axhline(ideal_abs, color="#4C956C", linewidth=1.2, linestyle="--")
    ax1.annotate(
        "total signal loss level",
        xy=(p_values[0], ideal_abs),
        xytext=(0, 5),
        textcoords="offset points",
        fontsize=7.5,
        color="#4C956C",
    )
    ax1.set_xscale("log")
    ax1.set_yscale("log")
    ax1.set_xlabel("depolarizing parameter $p$ (1q and 2q gates)")
    ax1.set_ylabel("selected-output error vs ideal")
    ax1.legend(frameon=False, fontsize=8, loc="lower right")
    ax1.grid(axis="y", which="both", color="#D8D8D8", linewidth=0.5)
    ax1.spines[["top", "right"]].set_visible(False)

    ax2.plot(
        p_values,
        positive["direct_postselection_acceptance"],
        marker="o",
        markersize=4.5,
        linewidth=2.0,
        color="#276FBF",
        label="noisy acceptance",
    )
    ideal_post = float(exact[exact["depolarizing_p"] == 0.0].iloc[0][
        "direct_postselection_acceptance"
    ])
    ax2.axhline(
        ideal_post, color="#4C956C", linewidth=1.2, linestyle="--", label="ideal acceptance"
    )
    mixed_acceptance = 2.0 ** (-int(reference["sparse_work_qubit_count"]))
    ax2.axhline(
        mixed_acceptance,
        color="#8A8A8A",
        linewidth=1.0,
        linestyle=":",
        label=rf"mixed work register ($2^{{-{int(reference['sparse_work_qubit_count'])}}}$)",
    )
    ax2.set_xscale("log")
    ax2.set_xlabel("depolarizing parameter $p$ (1q and 2q gates)")
    ax2.set_ylabel("postselection acceptance")
    ax2.set_ylim(0.0, 1.0)
    ax2.legend(frameon=False, fontsize=8, loc="upper right")
    ax2.grid(axis="y", color="#D8D8D8", linewidth=0.5)
    ax2.spines[["top", "right"]].set_visible(False)

    FIGURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIGURE_PATH, bbox_inches="tight")
    plt.close(fig)


def _run_checkpointed_sweep() -> tuple[pd.DataFrame, pd.DataFrame, dict, dict]:
    """Resumable sweep: every ~4.5-minute density-matrix evolution is checkpointed."""

    from robust_qsvt_se.qsvt.generic_sparse_execution import validate_compiled_statevector
    from robust_qsvt_se.qsvt.sparse_integrated_chain import estimate_signed_selected_output

    done = _load_checkpoints()
    canonical = rebuild_canonical()
    compiled = rebuild_dimension_anchor_4x4(canonical)
    print(f"[noise] rebuilt and identity-verified {ANCHOR_4X4_ID}", flush=True)

    primary = compiled.functional_spec.primary_functional_id
    bundle = compiled.functional_circuits[primary]
    flag_qubit = int(bundle.register_layout["postselection_flag_qubit"])
    readout_qubit = int(bundle.register_layout["readout_qubit"])
    physical_scale = float(compiled.recovery_factors[primary])

    statevector = validate_compiled_statevector(compiled)
    reference_row = next(
        row for row in statevector.functional_rows if row["functional_id"] == primary
    )
    reference_output = float(reference_row["statevector_selected_output"])
    reference_postselection = float(
        statevector.metrics["sparse_postselection_probability"]
    )
    ideal_joint = statevector.exact_joint_distributions[primary]

    reduced_measured = reduce_to_noise_basis(bundle.circuit)
    reduced_direct = reduce_to_noise_basis(compiled.direct_postselection_circuit)
    gate_counts = noise_basis_gate_counts(reduced_measured)
    print(
        f"[noise] noise basis: {gate_counts['total_noisy_gates']} noisy gates "
        f"({gate_counts['noisy_one_qubit_gates']} 1q, "
        f"{gate_counts['noisy_two_qubit_gates']} 2q), depth {gate_counts['depth']}",
        flush=True,
    )

    exact_rows: list[dict] = []
    sampled_rows: list[dict] = []
    for p in DEPOLARIZING_SWEEP:
        model = build_depolarizing_model(p)
        key = f"exact_functional:p={p:g}"
        if key not in done:
            import time as _time

            started = _time.perf_counter()
            distribution = exact_noisy_joint_distribution(
                reduced_measured,
                model,
                postselection_flag_qubit=flag_qubit,
                readout_qubit=readout_qubit,
            )
            _checkpoint(
                key, {"distribution": distribution,
                      "runtime_seconds": _time.perf_counter() - started}
            )
            done[key] = {"distribution": distribution,
                         "runtime_seconds": _time.perf_counter() - started}
            print(f"[noise] {key} done", flush=True)
        distribution = done[key]["distribution"]
        if p == 0.0:
            drift = max(
                abs(float(distribution[k]) - float(ideal_joint[k])) for k in distribution
            )
            if drift > 1.0e-9:
                raise RuntimeError(
                    f"ideal noisy-path distribution drifts from statevector by {drift}"
                )
        key = f"exact_direct:p={p:g}"
        if key not in done:
            acceptance = exact_noisy_marginal_zero(
                reduced_direct,
                model,
                qubit=int(compiled.register_allocation["postselection_flag"][0]),
            )
            _checkpoint(key, {"acceptance": acceptance})
            done[key] = {"acceptance": acceptance}
            print(f"[noise] {key} done", flush=True)
        direct_acceptance = float(done[key]["acceptance"])
        derived = selected_output_from_distribution(distribution, physical_scale)
        exact_rows.append(
            {
                "workload_id": compiled.workload_id,
                "functional_id": primary,
                "depolarizing_p": float(p),
                "estimator": "exact_noisy_density_matrix",
                **{f"p_{k}": float(v) for k, v in distribution.items()},
                "selected_output": derived["selected_output"],
                "statevector_reference": reference_output,
                "absolute_error_vs_ideal": abs(
                    derived["selected_output"] - reference_output
                ),
                "relative_error_vs_ideal": abs(
                    derived["selected_output"] - reference_output
                )
                / abs(reference_output),
                "signal_retention_fraction": derived["selected_output"]
                / reference_output,
                "interference_acceptance_probability": derived[
                    "interference_acceptance_probability"
                ],
                "direct_postselection_acceptance": direct_acceptance,
                "ideal_postselection_probability": reference_postselection,
                "runtime_seconds": float(done[f"exact_functional:p={p:g}"].get(
                    "runtime_seconds", float("nan")
                )),
            }
        )
        for seed in SAMPLING_SEEDS:
            key = f"sampled_functional:p={p:g}:seed={seed}"
            if key not in done:
                counts = sampled_noisy_counts(
                    reduced_measured, model, shots=SHOTS_PER_SEED, seed=seed
                )
                _checkpoint(key, {"counts": counts})
                done[key] = {"counts": counts}
                print(f"[noise] {key} done", flush=True)
            counts = {k: int(v) for k, v in done[key]["counts"].items()}
            estimate = estimate_signed_selected_output(
                counts, physical_scale=physical_scale
            )
            if seed == SAMPLING_SEEDS[0]:
                key = f"sampled_direct:p={p:g}:seed={seed}"
                if key not in done:
                    direct_counts = sampled_noisy_counts(
                        reduced_direct, model, shots=SHOTS_PER_SEED, seed=seed
                    )
                    _checkpoint(key, {"counts": direct_counts})
                    done[key] = {"counts": direct_counts}
                    print(f"[noise] {key} done", flush=True)
                accepted = int(done[key]["counts"].get("0", 0))
            else:
                accepted = -1  # direct circuit sampled once per noise level
            sampled_rows.append(
                {
                    "workload_id": compiled.workload_id,
                    "functional_id": primary,
                    "depolarizing_p": float(p),
                    "estimator": "sampled_noisy_counts",
                    "shots": int(SHOTS_PER_SEED),
                    "seed": int(seed),
                    "count_00": int(counts.get("00", 0)),
                    "count_01": int(counts.get("01", 0)),
                    "count_10": int(counts.get("10", 0)),
                    "count_11": int(counts.get("11", 0)),
                    "selected_output": float(estimate["selected_output_estimate"]),
                    "analytic_standard_error": float(estimate["analytic_standard_error"]),
                    "statevector_reference": reference_output,
                    "absolute_error_vs_ideal": abs(
                        float(estimate["selected_output_estimate"]) - reference_output
                    ),
                    "direct_postselection_accepted": accepted,
                    "direct_postselection_acceptance": (
                        accepted / float(SHOTS_PER_SEED) if accepted >= 0 else float("nan")
                    ),
                }
            )
    reference = {
        "workload_id": compiled.workload_id,
        "functional_id": primary,
        "statevector_selected_output": reference_output,
        "ideal_postselection_probability": reference_postselection,
        "physical_scale": physical_scale,
        "postselection_flag_qubit": flag_qubit,
        "readout_qubit": readout_qubit,
        "qubits": int(bundle.circuit.num_qubits),
        "sparse_work_qubit_count": len(bundle.register_layout["sparse_work_qubits"]),
        "workload_digest": compiled.workload_digest,
        "ideal_joint_distribution_max_drift_check": "passed (atol 1e-9)",
    }
    return pd.DataFrame(exact_rows), pd.DataFrame(sampled_rows), gate_counts, reference


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    exact, sampled, gate_counts, reference = _run_checkpointed_sweep()
    exact.to_csv(OUTPUT_DIR / "exact_noise_rows.csv", index=False)
    sampled.to_csv(OUTPUT_DIR / "sampled_noise_rows.csv", index=False)
    pd.DataFrame([gate_counts]).to_csv(
        OUTPUT_DIR / "noise_basis_gate_counts.csv", index=False
    )
    (OUTPUT_DIR / "reference.json").write_text(
        json.dumps(reference, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    TABLE_PATH.write_text(
        build_table(exact, sampled, gate_counts, reference), encoding="utf-8"
    )
    build_figure(exact, sampled, reference)

    provenance = {
        "study_id": "noise_model_boundary_v1",
        "generated_utc": datetime.now(UTC).isoformat(),
        "generator": "scripts/run_noise_model_boundary.py",
        "git_commit": _git_commit(),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "evidence_tier": "noisy_simulator_execution",
        "workload_id": ANCHOR_4X4_ID,
        "noise_model": {
            "type": "uniform_depolarizing",
            "basis": list(NOISE_BASIS),
            "one_qubit_noisy_gates": ["rz", "sx", "x"],
            "two_qubit_noisy_gates": ["cx"],
            "sweep": [p for p in DEPOLARIZING_SWEEP],
        },
        "sampling": {"shots_per_seed": SHOTS_PER_SEED, "seeds": list(SAMPLING_SEEDS)},
        "simulator": "qiskit-aer density_matrix, single-threaded",
        "claim_boundary": (
            "Noisy classical simulation of one small circuit under a uniform depolarizing "
            "model; not a hardware calibration, error-mitigation, or hardware-readiness "
            "claim."
        ),
        "manuscript_assets": [
            str(TABLE_PATH.relative_to(ROOT)),
            str(FIGURE_PATH.relative_to(ROOT)),
        ],
    }
    (OUTPUT_DIR / "provenance.json").write_text(
        json.dumps(provenance, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _write_manifest(OUTPUT_DIR)
    print(
        exact[
            [
                "depolarizing_p",
                "selected_output",
                "absolute_error_vs_ideal",
                "signal_retention_fraction",
                "direct_postselection_acceptance",
            ]
        ].to_string(index=False)
    )


if __name__ == "__main__":
    main()
