#!/usr/bin/env python3
"""Register the rectangular 8x4 zero-padded workload (W3, strongly-rec #9; stretch A6).

One tall 8x4 IEEE-14 weighted-Jacobian block (frozen outcome-independent extractor, matrix
seed 123) is zero-padded to 8x8 and compiled through the UNCHANGED generic sparse-QSVT
compiler path with the frozen canonical degree-31 polynomial/phases.  The study verifies the
exact classical padding equivalence, runs the standard statevector validation, counts
transpiled resources, and executes genuine Aer finite shots at fixed seeds.

Outputs: outputs/rectangular_padded_workload/ (CSVs, provenance, manifest, checksums) and
manuscript/tables/rectangular_padded_workload.tex.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from dataclasses import replace
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from robust_qsvt_se.qsvt.ft_workload_rebuild import rebuild_canonical  # noqa: E402
from robust_qsvt_se.qsvt.generic_sparse_execution import (  # noqa: E402
    build_resource_evidence,
    prepare_compiled_execution,
    run_compiled_shots,
    validate_compiled_statevector,
)
from robust_qsvt_se.qsvt.rectangular_padded_workload import (  # noqa: E402
    RECT_COLS,
    RECT_ROWS,
    WORKLOAD_ID,
    build_padded_workload,
    build_rectangular_block,
    classical_padding_equivalence,
    statevector_rectangular_consistency,
    zero_pad,
)

OUTPUT_DIR = ROOT / "outputs" / "rectangular_padded_workload"
TABLE_PATH = ROOT / "manuscript" / "tables" / "rectangular_padded_workload.tex"
GENERATED_HEADER = "% GENERATED by scripts/run_rectangular_padded_workload.py"
SHOT_COUNTS = (100_000,)
SHOT_SEEDS = (0, 1, 2)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _git_commit() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return "unavailable"


def _write_manifest(directory: Path) -> None:
    artifacts = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file() or path.name in {"manifest.json", "checksums.sha256"}:
            continue
        artifacts.append(
            {
                "path": str(path.relative_to(directory)),
                "sha256": _sha256(path),
                "size_bytes": path.stat().st_size,
            }
        )
    (directory / "manifest.json").write_text(
        json.dumps({"artifact_count": len(artifacts), "artifacts": artifacts}, indent=2) + "\n",
        encoding="utf-8",
    )
    (directory / "checksums.sha256").write_text(
        "".join(f"{item['sha256']}  {item['path']}\n" for item in artifacts),
        encoding="utf-8",
    )


def _sci(value: float, digits: int = 2) -> str:
    value = float(value)
    if value == 0.0:
        return "0"
    exponent = int(np.floor(np.log10(abs(value))))
    return rf"${value / 10**exponent:.{digits}f}\times10^{{{exponent}}}$"


def build_table(summary: dict, resource: dict, shots_summary: pd.DataFrame) -> str:
    shot_row = shots_summary.iloc[0]
    rows = [
        ("Rectangular block / padding", r"$8\times4$ real columns zero-padded to $8\times8$"),
        ("Support coordinates / slots", f"{summary['support_count']} / {summary['slots']}"),
        ("QSVT degree (frozen canonical phases)", f"{summary['degree']}"),
        (
            "Classical padding equivalence",
            rf"real-column gap {_sci(summary['max_abs_real_column_gap'])}; "
            rf"padded leak {_sci(summary['max_abs_padded_coordinate'])}",
        ),
        ("Block error $\\epsilon_{\\rm block}$", _sci(summary["epsilon_block"], 3)),
        ("QSVT/polynomial error $\\epsilon_{\\rm QSVT}$", _sci(summary["epsilon_qsvt"], 3)),
        (
            "Statevector vs rectangular quantized Ridge",
            _sci(summary["abs_gap_statevector_vs_rect_ridge"], 3),
        ),
        ("Postselection probability $p_{\\rm post}$", f"{summary['postselection']:.6f}"),
        (
            "Transpiled gates / depth / qubits",
            f"{int(resource['transpiled_gate_count']):,} / "
            f"{int(resource['transpiled_depth']):,} / "
            f"{int(resource['total_simultaneously_live_qubits'])}",
        ),
        (
            f"{int(shot_row['shots']):,}-shot mean abs.\\ error vs statevector "
            f"({int(shot_row['seed_count'])} seeds)",
            _sci(shot_row["mean_absolute_error_vs_statevector"], 3),
        ),
    ]
    body = [f"{name} & {value} \\\\" for name, value in rows]
    caption = (
        "Rectangular zero-padded sparse workload: one tall $8\\times4$ IEEE-14 "
        "weighted-Jacobian block (frozen outcome-independent extractor, matrix seed 123) "
        "embedded in the square power-of-two compiler by zero-padding four state columns and "
        "compiled through the unchanged canonical degree-31 path. Zero-padding is exactly "
        "equivalent to the rectangular Ridge problem (padded coordinates carry zero weight "
        "and output), so this registers genuinely rectangular semantics inside the existing "
        "square-only wrapper; statevector, transpiled-resource, and finite-shot rows use the "
        "same evidence conventions as the two frozen $8\\times8$ workloads."
    )
    lines = [
        GENERATED_HEADER,
        "% Source: outputs/rectangular_padded_workload/",
        r"\begin{table}[t]",
        rf"\caption{{{caption}}}",
        r"\label{tab:rectangular_padded_workload}",
        r"\centering",
        r"\footnotesize",
        r"\begin{tabular}{@{}p{0.55\columnwidth}p{0.38\columnwidth}@{}}",
        r"\toprule",
        r"Quantity & Value \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    rectangular, residual, _rows, _cols = build_rectangular_block()
    canonical = rebuild_canonical()
    compiled, metadata = build_padded_workload(canonical)
    equivalence = classical_padding_equivalence(
        rectangular, zero_pad(rectangular), residual, metadata["alpha"]
    )
    if not equivalence["equivalent"]:
        raise RuntimeError(f"padding equivalence violated: {equivalence}")

    statevector = validate_compiled_statevector(compiled)
    primary = compiled.functional_spec.primary_functional_id
    primary_row = next(
        row for row in statevector.functional_rows if row["functional_id"] == primary
    )
    consistency = statevector_rectangular_consistency(compiled, primary_row)

    execution = replace(
        compiled.execution_spec,
        shot_counts=SHOT_COUNTS,
        simulator_seeds=SHOT_SEEDS,
        execute_statevector=True,
        execute_finite_shots=True,
    )
    compiled = replace(compiled, execution_spec=execution)
    prepared = prepare_compiled_execution(compiled)
    resource = build_resource_evidence(compiled, prepared)
    shots = run_compiled_shots(compiled, statevector, prepared)

    pd.DataFrame([{**metadata, **equivalence, **consistency}]).to_csv(
        OUTPUT_DIR / "workload_registration.csv", index=False
    )
    pd.DataFrame(statevector.functional_rows).to_csv(
        OUTPUT_DIR / "statevector_validation.csv", index=False
    )
    pd.DataFrame([statevector.metrics]).to_csv(
        OUTPUT_DIR / "statevector_metrics.csv", index=False
    )
    pd.DataFrame([resource.record]).to_csv(OUTPUT_DIR / "resource_ledger.csv", index=False)
    pd.DataFrame(resource.register_rows).to_csv(
        OUTPUT_DIR / "register_ledger.csv", index=False
    )
    pd.DataFrame(shots.rows).to_csv(OUTPUT_DIR / "shot_rows.csv", index=False)
    shots_summary = pd.DataFrame(shots.summary_rows)
    shots_summary.to_csv(OUTPUT_DIR / "shot_summary.csv", index=False)

    summary = {
        "support_count": len(compiled.support_spec.coordinates),
        "slots": compiled.wrapper.slots,
        "degree": metadata["degree"],
        "max_abs_real_column_gap": equivalence["max_abs_real_column_gap"],
        "max_abs_padded_coordinate": equivalence["max_abs_padded_coordinate"],
        "epsilon_block": float(statevector.metrics["epsilon_block"]),
        "epsilon_qsvt": float(statevector.metrics["epsilon_qsvt"]),
        "abs_gap_statevector_vs_rect_ridge": consistency[
            "abs_gap_statevector_vs_rect_ridge"
        ],
        "postselection": float(statevector.metrics["sparse_postselection_probability"]),
    }
    primary_shots = shots_summary.loc[shots_summary["functional_id"] == primary]
    TABLE_PATH.write_text(
        build_table(summary, resource.record, primary_shots), encoding="utf-8"
    )

    provenance = {
        "study_id": "rectangular_padded_workload_v1",
        "generated_utc": datetime.now(UTC).isoformat(),
        "generator": "scripts/run_rectangular_padded_workload.py",
        "git_commit": _git_commit(),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "workload_id": WORKLOAD_ID,
        "rectangular_shape": [RECT_ROWS, RECT_COLS],
        "matrix_seed": 123,
        "shot_counts": list(SHOT_COUNTS),
        "shot_seeds": list(SHOT_SEEDS),
        "evidence_tiers": {
            "statevector": "statevector circuit execution (classical simulator)",
            "resources": "transpiled final measured circuit",
            "shots": "finite-shot simulator execution (Aer counts)",
            "padding_equivalence": "classical exact computation",
        },
        "claim_boundary": (
            "Zero-padded embedding of one tall block; the compiler itself remains "
            "square-power-of-two only, and no general tall/wide compiler support is claimed."
        ),
        "manuscript_assets": [str(TABLE_PATH.relative_to(ROOT))],
    }
    (OUTPUT_DIR / "provenance.json").write_text(
        json.dumps(provenance, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _write_manifest(OUTPUT_DIR)
    print(
        f"[rect] {WORKLOAD_ID}: gates={resource.record['transpiled_gate_count']} "
        f"epsilon_qsvt={summary['epsilon_qsvt']:.3e} p_post={summary['postselection']:.4f} "
        f"shot_err={float(primary_shots.iloc[0]['mean_absolute_error_vs_statevector']):.3e}"
    )


if __name__ == "__main__":
    main()
